### ISSUE TITLE
사전교육과 사전 설명회 등에 참석 불가할 경우 대회 참여 제한되나요?

### ISSUE THREAD

**Issue by Karnian** [ai-starthon/AI_Starthon2019#1]
8월 중순까지 해외에 있어서 참석이 힘들것 같은데 이런경우 대회 참여가 제한되나요?

**Comment by taehee3088** [comment]
안녕하세요. 

사전교육은 참가신청을 하더라도 필참 항목은 아닙니다. 물론 참여제한이나 불이익도 없구요.^^
일정 상의 이유로 사전교육에 참가하지 못하신 참가팀들을 위해 
사전 교육내용 자료는 이메일로 공유드릴 수 있도록 할 예정입니다. 

고맙습니다.
