### ISSUE TITLE
참가 대상 자격요건에 대해서

### ISSUE THREAD

**Issue by sjkoo1989** [ai-starthon/AI_Starthon2019#10]
안녕하십니까?
저희 팀원들이 그룹 2로 참여하고자 합니다.

(1) 팀원들 중에는 반드시 창업자가 포함되어야하나요? 아니면 사원들간의 참석이 가능한가요?
(2) 팀원들 중 전문연구요원 / 산업기능요원등으로 현재 휴학 중인 학생 사원이 포함될 수 있나요?
(3) 회사에 입사예정인 팀원도 팀원으로써 참석이 가능할까요?

**Comment by aistarthonwaywai** [comment]
안녕하세요.

경진대회 및 사업화지원 대상은 아래의 조건으로 2리그로 구분됩니다.

1리그: 예비 창업자 및 창업 3년 미만 기업
2리그: 창업 3년 이상된 기업

문의주신 사항으로 볼때 예비창업 그룹에 포함되시는것 같습니다.
또한, 아래 답변도 참조해 주시기 바랍니다.

(1) 팀원들 중 창업자가 없으시면 예비 창업자로 간주됩니다.
(2) 팀원중 학생 사원도 포함 가능합니다.
(3) 입사 예정인 팀원도 팀원으로 참석 가능합니다.

고맙습니다.
