### ISSUE TITLE
Git ID 등록 부탁드립니다.

### ISSUE THREAD

**Issue by BOMS2** [ai-starthon/AI_Starthon2019#101]
팀명 SYF(Sensitive Yellow Fox)
이름 김보민
아이디 BOMS2

등록 요청드립니다. 감사합니다.

**Comment by Huffon** [comment]
팀명 마키나블랙
이름 허훈
아이디 huffon 
도 부탁드립니당!

**Comment by ghost** [comment]
팀명: 한날 여섯시
이름: 황정민
아이디: jeongming

등록 요청드립니다.
감사합니다.

**Comment by dudgus1727** [comment]
팀명 : 벤더스터 (venduster)
이름 : 이영현
아이디 : dudgus1727

등록 요청드립니다.

**Comment by nsml-admin** [comment]
윗분들 전부 등록되었으며 

아래 계정으로 접속가능합니다.
@Huffon         huffon-> Huffon 
@Jeongming  jeongming-> Jeongming
