### ISSUE TITLE
대학생의 경우 개인 참여시 최종 20팀 선발 불가인가요?

### ISSUE THREAD

**Issue by Karnian** [ai-starthon/AI_Starthon2019#11]
현재 학교 내 산학협력단에 문의하지 않고 개인적으로 팀을 꾸려 신청한 상황인데 이런 경우 최종 본선 진출 및 20팀 이내 선발에서 제외되나요?

**Comment by aistarthonwaywai** [comment]
대학생 또는 대학원생의 경우 최종 사업화 지원대상으로 선정되었을때
스스로 창업(사업자 등록 및 법인설립)이 가능하시다면 
산학협력단을 통하지 않고 개인으로 참여하실 수 있습니다.

이경우 예비창업자로 본선 및 사업화 지원 대상에 포함됩니다.

고맙습니다.
