### ISSUE TITLE
Git 아이디 등록 요청드립니다.

### ISSUE THREAD

**Issue by mkmdivy** [ai-starthon/AI_Starthon2019#111]
지키호이팀 

mkmdivy
wonjiky 
github 아이디 등록 요청 부탁드립니다.

**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**Question**

**Comment by nsml-admin** [comment]
안녕하세요
등록되었습니다.
확인부탁드려요 ~

**Comment by mkmdivy** [comment]
잘 작동합니다. 감사합니다!
