### ISSUE TITLE
사전교육 자료 관련

### ISSUE THREAD

**Issue by hiphil2000** [ai-starthon/AI_Starthon2019#12]
사전교육 자료가 홈페이지에 올라온다고 되어있었는데,

혹시 사전교육 자료를 언제쯤 받아볼 수 있을지 궁금합니다.

**Comment by aistarthonwaywai** [comment]
안녕하세요.

현재 영상 편집중에 있습니다.
금일 중에는 완료하여 홈페이지 게재할 예정입니다.
조금만 기다려 주세요~

고맙습니다.

**Comment by aistarthonwaywai** [comment]
안녕하세요.

사전교육 동영상은 홈페이지 <Share-사전교육 영상 바로가기>에서 확인하실 수 있으며,
아래 유투브에서도 시청하실 수 있습니다.

https://www.youtube.com/channel/UC8OW3iwqkLs61lFY8vWDozQ?view_as=subscriber

고맙습니다.
