### ISSUE TITLE
Detection문제 submit 관련 질문 드립니다.

### ISSUE THREAD

**Issue by HotaekHan** [ai-starthon/AI_Starthon2019#125]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**
HotaekHan

**Question**
Detection 관련 문제(10~13번)에 공통적으로 해당되는 질문인데요.
현재 submit -t로 확인했을 때와 submit 시 결과가 많이 달라서(submit 실행 시 항상 스코어가 0이 나옴), submit을 실행했을 때 flow와 input 및 output에 대해 문의 드립니다.

1) baseline 코드를 보면 data_local_loader.py에 Custom dataset과 data loader가 정의되어 있는데요. submit을 실행하면 해당 코드들의 영향을 받나요? 
즉, Custom dataset에 정의되어 있는 이미지 전처리(화이트닝 및 리사이즈)가 submit시에도 적용이 되나요? 만약 영향을 받는다면, submit시 gt값은 리사이즈가 된 이미지 스케일에 맞추어서 정의되어 있나요?

2) 대회 설명을 이해한 바로는, submit 관련해서 nsml에 binding하는 infer 함수만 수정하면 되는 것으로 이해를 하고 있는데요. 
baseline 코드를 보면 infer 함수로 root_path를 받아오게 되어 있습니다. 그러면 해당 path에 있는 test image들을 읽어서 결과를 baseline code와 같은 포맷( Nx4의 numpy array, N은 데이터 갯수)으로 output을 주면 되는걸로 이해를 하고 있습니다.
이 때 baseline에 정의된 data loader를 사용하지 않고, root_path에서 이미지 경로를 알아내서 이미지 한장씩 읽어와서 처리하여도 무방한가요? 그런데 이렇게 할 경우 각 row에 있는 결과가 어떤 이미지로부터 구해졌는지 정보가 없는데 평가에 지장은 없는건가요?

3) box output의 형식은 xmin, ymin, width, height가 맞나요?

4) 혹시 output의 box갯수가 GT의 box갯수보다 적거나 많으면 어떻게 처리해야 하나요?
즉, GT는 한 장의 이미지에 오직 1개의 Box만 있다는걸로 이해를 하고 있는데요. Prediction을 했을 때, 한 장의 이미지에서 결과가 하나도 안나오거나(미검출), 결과가 2개 이상이 나오면(오검출) 어떻게 처리해야 되나요?

학습 세션
team_57/13_idet_car/104

Submit 세션
team_57/13_idet_car/105

**Comment by hellbell** [comment]
Q1. 네 data_local_loader.py 의 CustomDataset class 가 불려오는 구조로 되어있고 CustomDataset 에서 전처리 부분을 수정하시면 반영될 것입니다. Submit 시 불러오는 테스트 데이터의 GT 값은 이미지 사이즈 (img_width, img_height)로 normalize되어 0~1 사이 값으로 되어 있습니다.

Q3. 네. prediction 도 0~1 사이 값으로 출력하시면 됩니다. 

Q4. Task 상 한장의 이미지에 하나의 box 만 존재하므로 후처리를 통해 해결하시면 될 듯합니다.

**Comment by HotaekHan** [comment]
@hellbell 현재 저는 베이스라인의 data loader를 사용하지 않아서, session을 run할때 data_local_loader.py를 session으로 복사하지 않는 상황인데요. 
만약 사용자가 data_local_loader.py를 복사해서 session으로 올리면 복사해서 올라간 파일의 내용이 적용된다는걸로 이해가 되는데 제대로 이해한게 맞을까요? loader 파일의 위치는 entry파일과 동일한 위치에 있어야 하나요?
그리고 그러면 infer함수에서 data loader를 불러오는 부분은 수정을 하면 안되는건가요?? infer함수에서 수정을 하면 안되는 부분이 있으면 알려주시면 감사하겠습니다.

**Comment by HotaekHan** [comment]
추가적으로 말씀해주신 사항들을 submit -t옵션으로 확인할 수 있으면 디버깅 하는데 많은 도움이 될 것 같습니다.

**Comment by nsml-admin** [comment]
@HotaekHan 
유저가 data_loader.py를 수정해서 올린다고해도 `submit`때 호출되는 data_loader는 수정되지않습니다(`submit --test`포함)

말씀해주신대로 10~13번 문제 모두 infer함수에 root_path를 이미 주는 방식이라서(https://github.com/ai-starthon/AI_Starthon2019/blob/master/13_idet_car_baseline/data_loader.py#L20) 해당패스에서 이미지를 한장씩 읽어서 처리하면 될것같습니다. 

패스의 raw값을 알아내서 읽는방식이나 현재 방식이나 똑같은거라서, 가급적 data_loader파일을 통해서 진행해주시기 바랍니다.

**Comment by HotaekHan** [comment]
@nsml-admin root_path 경로에서 읽혀지는 이미지들의 순서는 신경쓰지 않아도 되나요? os.walk모듈의 경우 이름순으로 읽혀지는걸로 알고있는데요. 해당 모듈을 사용해도 무관할까요?

**Comment by hellbell** [comment]
@HotaekHan 
test data의 경우 %05d.jpg 의 형태로 존재하므로 이름 순서대로 읽으시면 됩니다. 
다만, os.walk 가 이름순으로 정렬을 하는지 제가 확실히 알지 못하는데요 baseline 구현을 참고하시면 도움이 될 것 같습니다 (참고: https://github.com/ai-starthon/AI_Starthon2019/blob/master/13_idet_car_baseline/data_local_loader.py#L37)
