### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by EungyeupKim** [ai-starthon/AI_Starthon2019#128]
nsml run을 하려고 하면, rate limit excess exceeded: remained time: 9m20s 이렇게 뜨는데, 이게 무슨 오류인가요..? ctrl+c로 key interrupt하고 난뒤, 다시 run하려고 하면 동일한 오류가 뜹니다..

**Comment by bluebrush** [comment]
@EungyeupKim 님, 해당 메시지는 과도한 접근 방지를 위한 방어 조치입니다. 
기계적으로 이루어 지며,  실패하는 command를 반복적으로 보낼 경우 발생합니다. 

#21 공지의 아래 문구에 해당하는 내용입니다. 
```
...
GPU 자원이 없는데, 지속해서 job을 실행하면 10분간 기다려야 함.(DDOS 방지)
...
```
