### ISSUE TITLE
submit 오류

### ISSUE THREAD

**Issue by EungyeupKim** [ai-starthon/AI_Starthon2019#131]
submit하려고 할때, 
............Inference the test set. The inference should be completed within 3600 seconds. 이후에

RuntimeError: DataLoader worker (pid 103) is killed by signal: Bus error.

라는 오류가 발생합니다. 혹시 무슨 오류인지 알 수 있을까요?

**Comment by nsml-admin** [comment]
세션네임을 알려주시면 확인해보겠습니다.
