### ISSUE TITLE
nsml run을 하려고 하는데, main.py: no such a file의 오류가 발생합니다.

### ISSUE THREAD

**Issue by EungyeupKim** [ai-starthon/AI_Starthon2019#137]
경로도 설정해줬고, 로그인도 해서 nsml 명령어는 다 되는것 같은데, main.py가 없다고 합니다.. 뭐가 문제일까요?

**Comment by bluebrush** [comment]
@EungyeupKim 님, 
아래 1가지를 비교해드리겠습니다.
1. nsml run -d [dataset] -e mysrc.py 일때: 현재 디렉토리에서 mysrc.py를 서버로 전송하여 실행.
2. nsml run -d [dataset]  일때, 현재 디렉토리의 ./main.py 파일을 서버로 전송하여 실행.

nsml run 실행시 -e 옵션을 주시 않을 경우, 현재 디렉토리의 main.py를 시작 소스로 간주(default)하여 진행합니다. 현재 위치에 main.py라는 파일이 없어서 발생하는 것 추정됩니다. 현재 디렉토리에 있는 파일을 확인해보실 것을 권해드립니다.
해결되지 않으실 경우, 
nsml run -d  ... 같이 실행 명령어 라인부터 오류 메시지 전체를 복사해서 붙여주시면 확인에 도움이 되겠습니다.

**Comment by EungyeupKim** [comment]
답변 감사합니다.
말씀해주신 두가지 중 저는 전자의 경우를 시행하고 있으며, 그럼에도 불고하고 오류가 발생하네요. 그전까진 잘 작동하다가, bash가 꺼졌다가 다시 키니 이런 문제가 발생하는것 같습니다. 환경변수 설정으로 nsml 응용프로그램이 있는 파일 path를 설정해줬고, nsml로 로그인을 하여 nsml을 타이핑하면 명령어 목록이 정상적으로 나오는데도 이러한 오류가 발생합니다.

오류 메시지 입니다.
$ nsml run -d 5_vcls_emotion --shm-size 24G -e main.py
time="2019/07/26 09:59:10.674" level=fatal msg="main.py: no such a file"

**Comment by bluebrush** [comment]
@EungyeupKim 님, 혹시, 아래 명령어들의 실형 결과를 확인할 수 있을까요?
```
ls -al
pwd
```

**Comment by EungyeupKim** [comment]
$ ls -al
total 13945
drwxr-xr-x 1 eungyeupkim 197121       0 7월  25 19:36  ./
drwxr-xr-x 1 eungyeupkim 197121       0 5월  12 20:20  ../
drwxr-xr-x 1 eungyeupkim 197121       0 5월  30 16:52  .astropy/
-rw-r--r-- 1 eungyeupkim 197121    8038 7월  26 00:12  .bash_history
drwxr-xr-x 1 eungyeupkim 197121       0 5월  30 20:54  .cache/
drwxr-xr-x 1 eungyeupkim 197121       0 5월  12 19:57  .conda/
drwxr-xr-x 1 eungyeupkim 197121       0 2월  18  2018  .eclipse/
-rw-r--r-- 1 eungyeupkim 197121      54 10월 29  2018  .gitconfig
drwxr-xr-x 1 eungyeupkim 197121       0 5월  20 06:24  .idlerc/
drwxr-xr-x 1 eungyeupkim 197121       0 7월  25 19:30  .ipynb_checkpoints/
drwxr-xr-x 1 eungyeupkim 197121       0 5월  23 10:03  .ipython/
drwxr-xr-x 1 eungyeupkim 197121       0 5월  29 21:43  .jupyter/
drwxr-xr-x 1 eungyeupkim 197121       0 5월  29 21:50  .matplotlib/
-rw-r--r-- 1 eungyeupkim 197121     381 7월  25 21:12  .nsml_auth
-rw-r--r-- 1 eungyeupkim 197121    1528 7월  25 21:12  .nsml_cert
drwxr-xr-x 1 eungyeupkim 197121       0 2월  22  2018  .p2/
drwxr-xr-x 1 eungyeupkim 197121       0 5월  11 20:06  .PyCharmCE2019.1/
drwxr-xr-x 1 eungyeupkim 197121       0 2월  18  2018  .ssh/
drwxr-xr-x 1 eungyeupkim 197121       0 2월  18  2018  .tooling/
drwxr-xr-x 1 eungyeupkim 197121       0 5월  11 20:14  .uniset/
drwxr-xr-x 1 eungyeupkim 197121       0 7월  14 19:06 '3D Objects'/
-rw-r--r-- 1 eungyeupkim 197121     496 1월  22  2018  AlphaBot_Test.py
-rw-r--r-- 1 eungyeupkim 197121     493 1월  22  2018  AlphaBot_Test_Right.py
drwxr-xr-x 1 eungyeupkim 197121       0 6월   6  2018  AppData/
lrwxrwxrwx 1 eungyeupkim 197121      34 6월   6  2018 'Application Data' -> /c/Users/김응엽/AppData/Roaming/
drwxr-xr-x 1 eungyeupkim 197121       0 7월  14 19:06  Contacts/
lrwxrwxrwx 1 eungyeupkim 197121      62 6월   6  2018  Cookies -> /c/Users/김응엽/AppData/Local/Microsoft/Windows/INetCookies/
drwxr-xr-x 1 eungyeupkim 197121       0 7월  26 09:59  Desktop/
drwxr-xr-x 1 eungyeupkim 197121       0 7월  14 19:06  Documents/
drwxr-xr-x 1 eungyeupkim 197121       0 7월  22 15:32  Downloads/
drwxr-xr-x 1 eungyeupkim 197121       0 7월  21 13:30  Dropbox/
drwxr-xr-x 1 eungyeupkim 197121       0 2월  18  2018  eclipse/
drwxr-xr-x 1 eungyeupkim 197121       0 2월  22  2018  eclipse-workspace/
drwxr-xr-x 1 eungyeupkim 197121       0 7월  16 11:44  Favorites/
-rw-r--r-- 1 eungyeupkim 197121     501 2월  21  2018  forward2.py
drwxr-xr-x 1 eungyeupkim 197121       0 7월  26 00:15 'Google 드라이브'/
drwxr-xr-x 1 eungyeupkim 197121       0 5월   8 11:34  IntelGraphicsProfiles/
drwxr-xr-x 1 eungyeupkim 197121       0 7월  14 19:06  Links/
lrwxrwxrwx 1 eungyeupkim 197121      32 6월   6  2018 'Local Settings' -> /c/Users/김응엽/AppData/Local/
drwxr-xr-x 1 eungyeupkim 197121       0 12월 13  2017  MicrosoftEdgeBackups/
drwxr-xr-x 1 eungyeupkim 197121       0 7월  14 19:06  Music/
lrwxrwxrwx 1 eungyeupkim 197121      28 6월   6  2018 'My Documents' -> /c/Users/김응엽/Documents/
lrwxrwxrwx 1 eungyeupkim 197121      70 6월   6  2018  NetHood -> '/c/Users/김응엽/AppData/Roaming/Microsoft/Windows/Network Shortcuts'/
-rw-r--r-- 1 eungyeupkim 197121 9699328 7월  26 00:12  NTUSER.DAT
-rw-r--r-- 1 eungyeupkim 197121 2629632 6월   6  2018  ntuser.dat.LOG1
-rw-r--r-- 1 eungyeupkim 197121   40960 6월   6  2018  ntuser.dat.LOG2
-rw-r--r-- 1 eungyeupkim 197121   65536 6월   6  2018  NTUSER.DAT{7553eb7b-68e6-11e8-b05c-88d7f6db8f45}.TM.blf
-rw-r--r-- 1 eungyeupkim 197121  524288 6월   6  2018  NTUSER.DAT{7553eb7b-68e6-11e8-b05c-88d7f6db8f45}.TMContainer00000000000000000001.regtrans-ms
-rw-r--r-- 1 eungyeupkim 197121  524288 6월   6  2018  NTUSER.DAT{7553eb7b-68e6-11e8-b05c-88d7f6db8f45}.TMContainer00000000000000000002.regtrans-ms
-rw-r--r-- 1 eungyeupkim 197121      20 6월   6  2018  ntuser.ini
drwxr-xr-x 1 eungyeupkim 197121       0 7월  26 00:13  OneDrive/
drwxr-xr-x 1 eungyeupkim 197121       0 7월  14 19:06  Pictures/
lrwxrwxrwx 1 eungyeupkim 197121      70 6월   6  2018  PrintHood -> '/c/Users/김응엽/AppData/Roaming/Microsoft/Windows/Printer Shortcuts'/
-rw-r--r-- 1 eungyeupkim 197121     600 1월  23  2018  PUTTY.RND
drwxr-xr-x 1 eungyeupkim 197121       0 7월  23 15:09  PycharmProjects/
lrwxrwxrwx 1 eungyeupkim 197121      59 6월   6  2018  Recent -> /c/Users/김응엽/AppData/Roaming/Microsoft/Windows/Recent/
drwxr-xr-x 1 eungyeupkim 197121       0 10월 13  2018  Roaming/
drwxr-xr-x 1 eungyeupkim 197121       0 7월  14 19:06 'Saved Games'/
drwxr-xr-x 1 eungyeupkim 197121       0 7월  14 19:06  Searches/
lrwxrwxrwx 1 eungyeupkim 197121      59 6월   6  2018  SendTo -> /c/Users/김응엽/AppData/Roaming/Microsoft/Windows/SendTo/
drwxr-xr-x 1 eungyeupkim 197121       0 9월   9  2017  source/
lrwxrwxrwx 1 eungyeupkim 197121      62 6월   6  2018  Templates -> /c/Users/김응엽/AppData/Roaming/Microsoft/Windows/Templates/
drwxr-xr-x 1 eungyeupkim 197121       0 2월   9  2018  UNISET/
-rw-r--r-- 1 eungyeupkim 197121  102969 7월  25 19:36  Untitled1.ipynb
drwxr-xr-x 1 eungyeupkim 197121       0 7월  14 19:06  Videos/
drwxr-xr-x 1 eungyeupkim 197121       0 5월  11 20:14 '새 폴더'/
lrwxrwxrwx 1 eungyeupkim 197121      63 6월   6  2018 '시작 메뉴' -> '/c/Users/김응엽/AppData/Roaming/Microsoft/Windows/Start Menu'/

$ pwd
/c/Users/김응엽

입니다. 
혹시몰라 bash에서 경로를 nsml_client.windows.amd64.hack폴더가 있는 디렉토리에서 동일한 명령어를 수행했음에도 ls -al의 명령어엔 같은 결과가 나왔음을 알려드립니다.

**Comment by EungyeupKim** [comment]
디렉토리를 잘못 정해줘서 발생한 문제였습니다. 해결하였습니다. 감사합니다 :)
