### ISSUE TITLE
참가자격 관련질문입니다.

### ISSUE THREAD

**Issue by seungyuns** [ai-starthon/AI_Starthon2019#14]
안녕하세요. 저희 회사는 4년차 스타트업입니다.
그런데 관련 질문에서 스타트업 창업자가 멤버에 속해있지 않으면 예비창업자로 간주한다는 답변을 봐서요 질문드립니다.

1) 사업등록증에 있는 회사 대표님이 팀원에 속해있지않으면 사업자등록증을 보내도 예비창업자로 간주되어 대회에 참여하게 되는지 궁금합니다.

2) 그렇다면 혹시 지금이라도 대표님을 팀원으로 넣어서 진행할 수 있는지 궁금합니다. 아니면 4년차 스타트업기업이지만 대표님이 팀원에 속해있지않으면 예비창업자로서 대회에 참여할 수 있는지 궁금합니다.

**Comment by aistarthonwaywai** [comment]
안녕하세요.

사업자등록증상의 대표가 팀원에 포함되지 않더라도
개업년월일을 기준으로 3년 이상이면 2리그로 분류됩니다.

고맙습니다.
