### ISSUE TITLE
submit error 

### ISSUE THREAD

**Issue by iyyun** [ai-starthon/AI_Starthon2019#145]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**Question**

nsml submit -t 명령어 에서는 에러 없이 동작 했지만... 

-t 를 제거 하면 다음과 같이 에러가 발생 합니다

Usage: nsml logs [OPTIONS] SESSIONError: Invalid value for "SESSION": Cannot logs [team_53/10_idet5_food/14] (Only nsml rm is valid for submit sessions)

어떤  문제인가요?

**Comment by nsml-admin** [comment]
https://github.com/ai-starthon/AI_Starthon2019/issues/90 이슈를 확인해보시기 바랍니다.
