### ISSUE TITLE
NSML login 문제

### ISSUE THREAD

**Issue by Kyuhong** [ai-starthon/AI_Starthon2019#15]
nsml 로그인이 안됩니다.

nsml client에서는 "login failed: You are not a registered user" 라고 나옵니다.

login 시도와 동시에 github에서 메일로 "Please verify your device" 제목으로 

다음과 같은 내용이 전달 되고 있습니다.

 A sign in attempt requires further verification because we did not recognize your device. To complete the sign in, enter the verification code on the unrecognized device.

Device: Safari on Unknown
Verification code: ******

**Comment by bluebrush** [comment]
@Kyuhong  nipa.nsml.navercorp.com 의 login은 대회 시작시간인 17:00 시 경에 일괄 처리 예정입니다. 현재, 사용자 정보등 확인하고 있습니다.

**Comment by bluebrush** [comment]
@Kyuhong 
대회 시작후, Web UI에서는  "Please verify your device" 메시지를 받으시면, github id 생성시 등록하신 email로 발송된 메일을 확인하시어 해당 코드를 입력하시면 됩니다. github에서 강화된 인증으로 신규 device에 대한 확인 과정이 추가되어 발송되는 메시지입니다.
