### ISSUE TITLE
1_reg_dust 데이터셋 관련 문의사항

### ISSUE THREAD

**Issue by Hemistone** [ai-starthon/AI_Starthon2019#150]
**What is your NSML login ID?**
Hemistone

**Question**
안녕하세요, 1_reg_dust 데이터셋에 관련해서 궁금한 점이 있어 문의를 드립니다.

문의사항은 다음과 같습니다.
    1. 현재 Input에서 먼지 농도들은 시간단위로 있는 반면 날짜는 일 단위로만 기록되어 있는 상황인것 같은데 현재 
    데이터셋의 날짜에 시간 단위까지 추가하는 것을 고려해주실 수 있을까요?
    2. 괜찮으시다면 지역번호(0~9)에 대한 지역 또는 관측소를 알려주실 수 있을까요?

**Comment by jungwoo-ha** [comment]
@Hemistone 

1. 시간단위 정보는 문제의 난이도를 위해 일부러 제거했습니다. 다만 데이터 특성상 연속한 이전 5시간의 값이 나오니 큰 상관은 없을 것이라고 생각합니다.
2. 역시 문제 정의시에 문제 난이도 (미세먼지가 다른 문제 대비 입문과정 수준이라)를 다른 문제들과 어느정도 비슷하게 하기 위해 index값으로만 공개했구요. 챌린지 후 실제 값을 공개할 예정입니다. 
결론은 불편하시더라도 주어진 데이터 내에서 진행해주시면 감사하겠습니다. 챌린지 후 공개시에 시간과 장소가 포함된 데이터 공개 예정입니다.

**Comment by Hemistone** [comment]
답변 감사드립니다. 데이터가 제공되어있는 선에서 최대한 노력해보도록 하겠습니다!
