### ISSUE TITLE
딥러닝 프레임 워크

### ISSUE THREAD

**Issue by zzozzolev** [ai-starthon/AI_Starthon2019#157]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**
zzozzolev

**Question**
문제 해결에 반드시 파이토치, 텐서플로우, 케라스 같은 딥러닝 프레임 워크를 써야 하나요?
젠심과 같은 자연어 처리 오픈 소스만을 이용해도 괜찮은지 여쭤보고 싶습니다.

**Comment by jungwoo-ha** [comment]
pretrained NN 혹은 문제 해결에 완성된 모듈(OpenCV에서의 detector와 같은)이 아니면 오픈소스의 경우는 괜찮습니다. gensim이라면 LDA나 w2v 구현 라이브러리는 사용가능합니다. 다만 requirements.txt를 통해 docker에 install 필요합니다.
