### ISSUE TITLE
팀원이 각각 Submit가능한가요?

### ISSUE THREAD

**Issue by cycos83** [ai-starthon/AI_Starthon2019#16]
Github ID를 사용한다는 말만 있을 뿐

팀을 구별하기 위한 별도의 내용이 공지되어 있지 않은데요

팀원들이 개별적으로 자신의 ID로 Submit을 하면 어떻게 되는 건가요?

**Comment by bluebrush** [comment]
@cycos83 각 팀원의 github id로 submit해도 내부에서는 신청하실때 만드신 팀명으로 1개로 등록됩니다.
