### ISSUE TITLE
file integrity check error 문의

### ISSUE THREAD

**Issue by KwakSanghyuk** [ai-starthon/AI_Starthon2019#162]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**Question**
nsml run 후 file integrity check에서 같은 디렉토리에 임의로 작성해 둔 파일이 '~$NSML_0_STAT.xlsx' 라는 파일 이름으로 저장되어 level=fatal 파일명 오류 메시지가 발생하고 있습니다. 해결 방법을 알려주시면 감사하겠습니다.

**Comment by bluebrush** [comment]
@KwakSanghyuk 오류 사항이 정확하게 이해가 안되었습니다. 
오류메시지 전체를 알려주실 수 있나요?
추가로, 
엑셀을 실행중이시면 종료하시고, 재부팅 후, 빈 디렉토리에 nsml 다시 설치후 구동하시는 것은 어떠실까요?

**Comment by KwakSanghyuk** [comment]
현재 디렉토리에서 엑셀 파일을 지운 상태인데도 아래와 같이 오류가 발생하고 있습니다.

================

time="2019/07/26 23:37:12.397" level=info msg="Welcome to NSML!"

C:\Users\ksh\Desktop\nsml\4_cls_food>dir

 C:\Users\ksh\Desktop\nsml\4_cls_food 디렉터리

2019-07-26  오후 09:52    <DIR>          .
2019-07-26  오후 09:52    <DIR>          ..
2019-07-26  오전 11:45             1,207 data_loader.py
2019-07-26  오전 11:45             2,719 data_local_loader.py
2019-07-26  오전 11:45             1,811 evaluation.py
2019-07-26  오후 09:49             6,731 main.py
2019-07-26  오전 11:45               548 README.md
2019-07-26  오전 11:45               241 setup.py
               6개 파일              13,257 바이트
               2개 디렉터리  83,285,368,832 바이트 남음

C:\Users\ksh\Desktop\nsml\4_cls_food>nsml run -d 4_cls_food -g 1 --memory 16G --shm-size 16G --cpus 4 -e main.py
time="2019/07/26 23:38:10.027" level=info msg=".nsmlignore check - start"
time="2019/07/26 23:38:10.144" level=info msg=".nsmlignore check - done"
time="2019/07/26 23:38:10.281" level=info msg="file integrity check - start"
time="2019/07/26 23:38:10.293" level=info msg="~$NSML_4_STAT.xlsx: invalid filename character"
time="2019/07/26 23:38:10.303" level=info msg="valid filename characters are\nA B C D E F G H I J K L M N O P Q R S T U V W X Y Z\na b c d e f g h i j k l m n o p q r s t u v w x y z\n0 1 2 3 4 5 6 7 8 9 . _ -\n+   [ ] { } ( ) '"
time="2019/07/26 23:38:10.327" level=fatal msg="you can use a .nsmlignore file to ignore files and directories"

C:\Users\ksh\Desktop\nsml\4_cls_food>

**Comment by bluebrush** [comment]
@KwakSanghyuk 님, 새로운 폴더를 만드시고, 필요한 파일만 옮기셔서 실행하시면 될 것 같습니다. 
필요 없어진 폴더는 폴더째 'shift + delete'로 지우시면 어떨까 합니다.

**Comment by KwakSanghyuk** [comment]
새로 폴더를 만들고 파일을 옮겨 실행해도 동일한 현상이 나타납니다.
엑셀 파일도 삭제한 상태입니다.

==============
C:\Users\ksh\Desktop\nsml_client\4_cls_food>dir
 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 860B-0E9A

 C:\Users\ksh\Desktop\nsml_client\4_cls_food 디렉터리

2019-07-26  오후 09:52    <DIR>          .
2019-07-26  오후 09:52    <DIR>          ..
2019-07-26  오전 11:45             1,207 data_loader.py
2019-07-26  오전 11:45             2,719 data_local_loader.py
2019-07-26  오전 11:45             1,811 evaluation.py
2019-07-26  오후 09:49             6,731 main.py
2019-07-26  오전 11:45               548 README.md
2019-07-26  오전 11:45               241 setup.py
               6개 파일              13,257 바이트
               2개 디렉터리  83,342,569,472 바이트 남음

C:\Users\ksh\Desktop\nsml_client\4_cls_food>nsml run -d 4_cls_food -g 1 --memory 16G --shm-size 16G --cpus 4 -e main.py
time="2019/07/26 23:54:54.140" level=info msg=".nsmlignore check - start"
time="2019/07/26 23:54:54.277" level=info msg=".nsmlignore check - done"
time="2019/07/26 23:54:54.424" level=info msg="file integrity check - start"
time="2019/07/26 23:54:54.430" level=info msg="~$NSML_4_STAT.xlsx: invalid filename character"
time="2019/07/26 23:54:54.437" level=info msg="valid filename characters are\nA B C D E F G H I J K L M N O P Q R S T U V W X Y Z\na b c d e f g h i j k l m n o p q r s t u v w x y z\n0 1 2 3 4 5 6 7 8 9 . _ -\n+   [ ] { } ( ) '"
time="2019/07/26 23:54:54.454" level=fatal msg="you can use a .nsmlignore file to ignore files and directories"

C:\Users\ksh\Desktop\nsml_client\4_cls_food>

**Comment by bluebrush** [comment]
@KwakSanghyuk 탐색기에서 ~$NS 선택해서 삭제가 가능하신가요? 
디렉토리 새로 만들고 xlsx 파일 복사하지 않고 실행하면 어떻게 되나요?

**Comment by KwakSanghyuk** [comment]
현재 local directory에는 엑셀파일 자체가 없습니다.(삭제한 상태입니다)

원래 액셀 파일명은 'NSML_4_STAT.xlsx'이었습니다.

아마도 (제 추측이므로 정확하지 않을 수 있습니다) 

nsml run을 처리하면서 파일이 이미 서버 측으로 전송된 상태(혹은 파일이름만 전송)이면서

로컬과 서버측 인코딩 문제로(CP949 to UTF-8)로 파일 이름이 '~$NSML_4_STAT.xlsx'가 유사한 형태로 

변경되어 서버측에 저장된 것이 남아있어 문제가 되는 것이 아닐까 생각됩니다. 

현재 .nsmlignore가 작동하지 않으므로 제 local 측에서는 해결이 안되는 것 같습니다.

참고 부탁드립니다.

**Comment by KwakSanghyuk** [comment]
잘 해결되었습니다.

감사합니다.^^
