### ISSUE TITLE
session 삭제 요청 및 문의

### ISSUE THREAD

**Issue by sike6054** [ai-starthon/AI_Starthon2019#167]
1. session 중지 혹은 삭제 부탁드립니다.
- team_92/4_cls_food/64

2. 자원 할당량 조절해서 겨우 돌려놨더니 baseline epoch 100회 수행하는데 3일씩 걸리던데 정상인가요? 끝나고 보니 GPU 자원 활용도가 8%정도던데;; 로컬로 작업했으면 submit을 100회는 더 했을 시간을 날리고 있네요

**Comment by byc3230** [comment]
nsml rm -f session 치시면 강제 삭제 됩니다
