### ISSUE TITLE
12_idet_food 질문

### ISSUE THREAD

**Issue by jmpark0808** [ai-starthon/AI_Starthon2019#169]
안녕하세요 12_idet_food 에 관해서 질문이 있습니다.

베이스라인 코드를 보면 테스트 데이터의 label이 [ x/ width, , y/ height ,  w / width, h / height] 로 되어있는 것 같습니다.
(width : 이미지 가로 길이, height : 이미지 세로 길이)

그런데 data_local_loader.CustomDataset 의 __getitem__ 부분을 보시면 
inputs = self.transform(images)
width, height = images.size
targets = self.target_transform(targets, (width, height))
으로 되어있고 self.transform = get_transform 은 이미지를 (224, 224) 로 Resize 하는 과정을 포함하고 있습니다.
그러면 현재 target_transform은 Resize 된 이후의 가로, 세로 길이로 target 를 normalize 하는 형태로 되어있는데요.
테스트 데이터의 label도 같은 방식으로 처리가 되어있는 것인지 확인 부탁드립니다.

**Comment by heartcored98** [comment]
#168 저도 13번 task에서 비슷한 생각이 들어서 문의를 남겼습니다.
운영진분들의 답변이 기다려지네요 ㅠ

**Comment by heartcored98** [comment]
그런데 코드를 다시보니

inputs = self.transform(images)
width, height = images.size   
targets = self.target_transform(targets, (width, height))

transform 된 이미지는 inputs이고 가로 세로 길이는 원본 이미지인 images.size에서 가져오는 것이므로 transform과 상관없이 항상 원본의 가로 세로로 normalize되는 것 아닐까요?
