### ISSUE TITLE
트레이닝 중간에 Error : docker daemon timeout 이 발생하였습니다.

### ISSUE THREAD

**Issue by KwakSanghyuk** [ai-starthon/AI_Starthon2019#174]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**Question**

트레이닝을 진행 중 epoch 10 부근에서 제목처럼 오류가 발생하였습니다.

이에 대한 주의사항 이나 미리 대비할 수 있는 방법을 알려주시면 감사하겠습니다.

**Comment by bluebrush** [comment]
@KwakSanghyuk 님, 불편을 드려서 죄송합니다. 세션명 알려주시면 추가확인하도록 하겠습니다. 현재, 3개 node(6개 gpu)하드웨어 문제가 감지되어 조치중입니다. 참고부탁드립니다. docker timeout은 일반적인 경우는 아니며, docker 데몬의 응답이 없는 경우로 커널 또는 데몬 프로세스의 문제에 기인하는 경우가 많습니다. 따라서 사전 대처 방법은 없습니다.

**Comment by KwakSanghyuk** [comment]
team_42/4_cls_food/19 입니다.

답변해 주셔서 감사합니다.

**Comment by KwakSanghyuk** [comment]
아래 명령으로 에러가 난 세션이 삭제되지 않습니다.
삭제 부탁드립니다.

>nsml rm -f team_42/4_cls_food/19

Warning: Removing team_42/4_cls_food/19 is failed
Error: Session error: 'Failed to delete session [team_42/4_cls_food/19]'
time="2019/07/28 00:42:17.759" level=fatal msg="Internal server error"

**Comment by bluebrush** [comment]
@KwakSanghyuk 님, 해당 장비에 대한 조치중에 있습니다. 잠시 후 다시 안내하겠습니다.

**Comment by bluebrush** [comment]
@KwakSanghyuk님, 해당 장비의 조치가 완료되었습니다. 
학습 중이던 세션을 fork하여 재시작하실 수있습니다. 참고부탁드립니다.
https://n-clair.github.io/nipa-docs/_build/html/ko_KR/contents/session/fork_a_session.html?highlight=fork

**Comment by KwakSanghyuk** [comment]
감사합니다.
