### ISSUE TITLE
점수 계산 방식은 단순히 리더보드대로만 하나요?

### ISSUE THREAD

**Issue by Karnian** [ai-starthon/AI_Starthon2019#176]
점수 계산시 상위팀부터 차등 점수 지급인데 팀당 참여 가능 문제수가 3문제이기 때문에

설령 한 팀이 모든 문제에서 1등을 하더라도 최고점은 3천점이 됩니다.

그런데 이 경우 각 문제당 리더보드에서 2등팀들은 300점부터 시작인데

특정 문제에서 본인보다 상위 등수의 팀이 해당문제로 점수를 받지 않더라도 문제당 리더보드엔 반영이 되어 각 문제별 리더보드의 점수 그대로 반영되는건가요?

(ex. A팀 모든문제 1등, B팀 모든문제 2등 -> A팀 총점 3000, B팀 총점 900)

**Comment by byc3230** [comment]
유튜브 가이드 동영상으로는 그렇다고 들었습니다.

**Comment by bluebrush** [comment]
@Karnian 님, 점수 계산을 아래와 같습니다, 
#19 참고하시면, 각 문항별 점수를 구할 수 있습니다. 
참가 문제에 대한 제한이 없으며 20개 모두 풀수 있습니다. 
종합 점수는 푼 문제중 상위 3개 문제를 #19 배점표의 합으로 종합 점수를 구하고, 최종 leaderbord에 자동 게시됩니다.

**Comment by Karnian** [comment]
@bluebrush 
제 질문의 의도는 예시로 든 케이스의 경우 A팀이 모든문제에서 1등일 때 3천점을 가져가지만
3개의 문제에 대해서만 인정을 받는거니
나머지 문제들에선 2등인 B팀이 1등 인정을 받아 문제당 1천점을 받을 수 있는건지, 
아니면 점수상으론 A팀이 3천점만 가져가지만
그 외 문제들에서도 각 문제당 1등은 인정되어 B팀은 2등으로서의 점수만 받는지 여부에 대해서였습니다.

마치 올림픽에서 1,2,3위가 각각 금,은,동 수상할때 3위가 실격처리 당할경우 4위가 동메달 받는것 처럼요.

**Comment by stimong** [comment]
@bluebrush
그러면 혹시 1번째 모델 submit 에 0.8 이나왔는데
2번째 모델 submit 은 0.7 이 나왔다고하면
최종 submit 정확도가 반영되나요?
아니면 가장높은 정확도가 반영되나요?

**Comment by bluebrush** [comment]
@stimong 님, 여러번 submit하셔도 항상 best 점수가 반영됩니다. 부담없이 submit하셔도 됩니다.

**Comment by bluebrush** [comment]
@Karnian 님, 2등인 B팀은 1등을 인정받지는 못합니다.

**Comment by ildoonet** [comment]
@bluebrush 3개 이상의 영역에서 3등 이내에 들어도 리더보드 상에 메달이 표시되게 해주시면 어떨까요? 점수는 3천점으로 나오고, 해당 메달은 없어지는 상황이라서요~
