### ISSUE TITLE
test(submit) 시에 train data 접근

### ISSUE THREAD

**Issue by kevhahn97** [ai-starthon/AI_Starthon2019#177]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Mac
- **client version(please show nsml --version)**: Built: 2019-07-24T20:38:40+09:00
Go: go1.12.7

#### WEB
- **Brower (chrome, firfox, etc)**: chrome
- **URL**:

**What is your NSML login ID?**
kevhahn97

**Question**
안녕하세요. train 세션에서 train data를 통해 sentencepiece tokenizer를 학습시킨 뒤 test 시에 load하려고 했으나, test 세션으로 넘어가면서 모델이 삭제되는 것 같습니다. 그래서 test 시에 train data 에 접근하여 모델을 다시 학습하려고 하니, train data에 접근이 되지 않는 문제를 겪고 있습니다.
(1) tokenizer 모델을 test 시에 불러오는 방법
혹은
(2) test 시에 train data에 접근하는 방법
가능한 방법이 있는지 도움 부탁드립니다.
감사합니다.

**Comment by nsml-admin** [comment]
안녕하세요.

1. tokenizer모델을 test시에 불러올수있습니다. tokenizer를 nsml.save()함수를 통해서 저장한후에 새로운 세션에서는 nsml.load()함수를 통해서 저장된 세션의 데이터를(tokenizer) 가져올수있습니다.

    - A라는 세션에서 tokenizer를 저장하는 임의의 함수 `save()`를 만들고, `nsml.bind(save=save)`로 바인딩을 시킨후 nsml.save()를 통해서 저장합니다. 

    - `nsml model ls A`를 통해서 새로 tokenizer가 제대로 저장되었는지 확인하고

    - 코드상에서, tokenizer를 불러오는 방식이 담긴 임의의 함수 `load()`를 만든후에 마찬가지로 `nsml.bind(load=load)`로 바인딩하고 `nsml.load(checkpoint=NSML_CHECKPOINT, session=NSML_SESSEION)` 이런식으로 호출하는 코드를 넣으면 tokenizer는 로드가 됩니다. [참고](https://github.com/ai-starthon/AI_Starthon2019/blob/master/19_tcls_qa/main.py#L94-L119)

19번 문제를 참고하시면 도움이 될것같습니다.

2. test시에 train_data에는 접근할수가 없습니다.
