### ISSUE TITLE
다른 세션의 모델을 Load

### ISSUE THREAD

**Issue by SeongwoongCho** [ai-starthon/AI_Starthon2019#178]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**
SeongwoongJo

**Question**
Pretrained 모델은 허용이 안된다고 하셨는데 다른 세션의 데이터를 학습한 모델을 Load해서 transfer learning을 하는것은 허용되나요 ??

**Comment by bsy3719** [comment]
혹시 같은 세션에서 학습한 모델도 transfer learning이 가능한지도 여쭤봅니다!!

**Comment by bluebrush** [comment]
@SeongwoongJo 님, @bsy3719 님. 동일 데이터 셋 내에서 재학습은 허용됩니다. 다른 데이터셋에서 model을 가져오는 것은 안됩니다.
