### ISSUE TITLE
10번 음식 검출 경량화 문제의 training data에 대해 문의 드립니다.

### ISSUE THREAD

**Issue by comlhj1114** [ai-starthon/AI_Starthon2019#186]
10번 문제(음식 검출 경량화)의 training data에서 box의 크기가 image의 크기를 넘어서는 sample이 보이는 것 같습니다.
GT 파일의 format이 x, y, w, h로 알고 있는데 제가 느끼기에는(정확한 검증은 못하였지만), 일부 샘플이 x, y, h, w로 데이터가 들어가 있는 것 같습니다. 혹시 format에 오류가 있는 것은 아닌지 궁금합니다.

**Comment by jungwoo-ha** [comment]
@comlhj1114

훈련데이터가 크라우드 소싱으로 만들어지다 보니 다소 노이지한 것들이 있는 것 같습니다.(분량때문에 사실상 전수검사가 불가능 합니다 ㅠㅠ) 실세계에서도 다수 발생하는 일의 일환이기도 하다고 생각되는 데요. 데이터 전처리단에서 나름의 노하우로 처리 후 학습을 권장드립니다.

**Comment by comlhj1114** [comment]
@jungwoo-ha 
답변 감사드립니다.
