### ISSUE TITLE
submit하지않고 정확도출력방법

### ISSUE THREAD

**Issue by stimong** [ai-starthon/AI_Starthon2019#187]
기초적인 질문하나 드립니다.
nsml submit [모델]
하면 테스트셋에대한 최종적인 정확도를 확인가능한것같스니다.
submit안하고 (트레이닝셋말고) 최종제출과 동일한 정확도 확인 방법은 어떤것인가요?

local_eval 정확도와 동일한가요?

**Comment by bluebrush** [comment]
@stimong 님, 안녕하세요. 
submit을 하지 않고 TEST 셋으로 부터 정확도를 측정할 수는 없습니다. 
최종 제출을 많이 하셔도 상관없습니다. 순위는 best score 기준으로 부여됩니다.

또한 자신의 submit이력을 privat leaderboard를 통해서 확인 가능합니다. 
예를 들어, 아래 주소에서, 우측/상단의 public -> private으로 변경하시면 자신의 팀에서 제출한 과거 history를 확인하실 수 있습니다. 이중에서 가장 좋은 점수가 최종 submit에 자동으로 계산됩니다. 
https://nipa.nsml.navercorp.com/leaderboard/4_cls_food
