### ISSUE TITLE
team_259 submit 오류 발생

### ISSUE THREAD

**Issue by seunghokimj** [ai-starthon/AI_Starthon2019#192]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: macOS 10.14.5
- **client version(please show nsml --version)**:
Built: 2019-07-24T20:38:40+09:00
Go: go1.12.7
GOARCH: amd64
GOOS: darwin
Revision: 3644619550d2a7b6c1c50e8da9c96354ed93a0a1 (not-modified)

**What is your NSML login ID?**
seunghkoimj

**Question**

nsml submit team_259/17_tcls_intent/28 700
........
Building docker image. It might take for a while
.....Warning: team_259/17_tcls_intent/31 is already removed. It will be removed from nsml soon
Error: team_259/17_tcls_intent/31: launching is failed. Please contact dev team
FATA[2019/07/29 16:47:58.362] Internal server error                        

위와 같은 error  메시지가 계속 뜨면서 submit 이 안되고 있는데 확인 부탁드립니다.

**Comment by nsml-admin** [comment]
안녕하세요,
세션이 할당된 장비에 문제가 생겨서 발생한 에러로 확인됩니다.
현재는 해당장비들은 세션할당에서 제외되어있고 수리중에있습니다.
다시한번 시도해보시기바랍니다
불편을드려서 죄송합니다.
