### ISSUE TITLE
nsml rm 명령어가 동작하지 않습니다.

### ISSUE THREAD

**Issue by taeminlee** [ai-starthon/AI_Starthon2019#198]
allocation에서 더이상 진행이 안되는 session이 nsml rm 명령어로 delete되지 않음

nsml rm -f team_130/16_tcls_movie/31

**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:
- **Full command line**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

taeminlee

**What is name of session in problem? (bug message or screenshot)**

team_130/16_tcls_movie/31

**Steps to reproduce the problem**

```sh
nsml rm -f team_130/16_tcls_movie/31
Warning: Removing team_130/16_tcls_movie/31 is failed
Error: Session error: 'Failed to delete session [team_130/16_tcls_movie/31]'
time="2019/07/29 19:22:09.408" level=fatal msg="Internal server error"
```

**What is the expected behavior?**

**Suggested solutions**

**Comment by bluebrush** [comment]
@taeminlee 님, 불편을 드려서 죄송합니다. 해당 세션이 할당된 노드의 인프라 장애(GPU Error)인하여 작업 진행이 어려운 상태로 확인되었습니다. credit 60을 세션 장애에 대한 보상으로 충전하겠습니다.
