### ISSUE TITLE
이번 서류심사도 깃허브 랭킹으로 선발되나요?

### ISSUE THREAD

**Issue by limdongjin** [ai-starthon/AI_Starthon2019#2]
저번 AI 해커톤의 경우에는 참가자의 절반은 깃허브 랭킹 고순위자로 선발하고, 참가자의 절반은 랜덤으로 선발하였는데, 
이번에도 동일한 방법으로 서류심사가 이루어지는지 알수있을까요?

**Comment by taehee3088** [comment]
안녕하세요.

해당 대회의 경우 네이버 AI 해커톤과는 다르게,
Github 계정은 nsml 로그인 권한 부여를 위해 정보를 취합하는 것이고,
신청서 상의 질의에 대한 답변을 검토하여 서류심사가 이루어집니다. 
온라인 본선 진출은 최대 400팀까지 가능하기 때문에 신청팀이 400팀 이상일 경우에 서류심사를 진행할 예정입니다. 

감사합니다.
