### ISSUE TITLE
마감기간이 얼마남지 않았는데 답변을 받지 못하여 다시 문의드립니다.

### ISSUE THREAD

**Issue by seungyuns** [ai-starthon/AI_Starthon2019#20]
이번에 3년이상 스타트업 자격으로 지원한 초록소프트 신승윤 입니다.

다름이 아니고 이번에 회사 대표님은 참여를 안하고 직원끼리만 대회에 참여를 하게 되었습니다.

이런경우 자격을 유지할 수 있는지, 꼭 대표님이 팀원에 포함이 되어야 3년이상 스타트업 자격으로 대회참여가 가능한건지 궁금합니다.

지금이라도 대표님을 팀원에 추가할 수 있을까요?

**Comment by aistarthonwaywai** [comment]
안녕하세요. 

사업자등록증에 있는 대표가 팀원으로 참여하지 않아도
회사가 창립 후 3년 이상이면 2리그로 참여하실 수 있습니다. 

초록소프트는 사업자등록증 제출해 주셨고 창업 3년 이상 기업임을 확인하였습니다.

고맙습니다.
