### ISSUE TITLE
launching is failed. Please contact dev team

### ISSUE THREAD

**Issue by ilhwanh** [ai-starthon/AI_Starthon2019#203]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
Windows 10
- **client version(please show nsml --version)**:
Built: 2019-07-24T20:38:40+09:00
Go: go1.12.7
GOARCH: amd64
GOOS: windows
Revision: 3644619550d2a7b6c1c50e8da9c96354ed93a0a1 (not-modified)
Preconfigured connection: nipa-cli.nsml.navercorp.com
- **Full command line**:
nsml submit team_253/7_icls_face/55 0

**What is your NSML login ID?**
IlhwanHwang

**What is name of session in problem? (bug message or screenshot)**
team_253/7_icls_face/55 에서 파생된 submit 세션 team_253/7_icls_face/57 (자동으로 삭제됨) 

**Steps to reproduce the problem**
`> nsml submit team_253/7_icls_face/55 0`

**What is the expected behavior?**
단일 인덱스 답으로 제출되어야함.
지금은 어떤 방법으로 세션을 제출하려고 하여도 비슷한 에러가 나서 제출하지 못하고있습니다.

![image](https://user-images.githubusercontent.com/18319496/62054077-d6f63480-b253-11e9-8d5d-a78e8f6c880f.png)

![image](https://user-images.githubusercontent.com/18319496/62054098-e2496000-b253-11e9-8bf3-70b61c41005d.png)

**Comment by stimong** [comment]
저도 같은 증상입니다.

**Comment by seharanul17** [comment]
저도 4번 데이터에 대하여 두 번 submit을 시도했는데, 두 번 다 같은 증상입니다.

**Comment by seharanul17** [comment]
저는 몇 번 더 submit 했더니 해결됐습니다.

**Comment by ilhwanh** [comment]
```
if config.pause:
        nsml.paused(scope=locals())
```
가 없어서 생기는 문제였네요.
추가하고 해결되었습니다.
