### ISSUE TITLE
4 번문제 submit code 질문

### ISSUE THREAD

**Issue by kboseong** [ai-starthon/AI_Starthon2019#206]
안녕하세요 대회운영에 수고많으십니다.

4번 문제를 submit시 시간이 너무 오래걸려 질문드립니다. baseline code 의 _infer함수의 input인 model을 infer 안에서 cuda()로 gpu 에 올려주었음에도 불구하고, 일반 train, val loader에서의 속도보다 훨씬 느린 속도로 inference가 이루어지는 것 같습니다. (200 sample/s vs 2sample/s) 그래서 gpu사용량을 체킹하면, gpu를 사용하지 않는 것으로 보입니다. 혹시 해당 문제에서 gpu 사용을 위해서 따로 적용해주어야하는 것이 있나요?

**Comment by stimong** [comment]
다른경우긴하지만 7번문제 gpu사용량은 있는데 30분넘게 summit 되고있습니다. 원래 30분단위로도 넘어갈수있나요?

**Comment by nsml-admin** [comment]
안녕하세요!


GPU사용을 위해서 따로 적용해주어야 할것은 세션을 실행시킬때 gpu갯수를 셋팅해주는것밖에없습니다.(기본값으로 1개는 셋팅되어서 실행됩니다.) 그외에 코드도 지피유를 사용하는 모드로 변경해주신후 실행시키면 될것같습니다.

현재 타임아웃은 1시간이라서 30분이 넘어가도 딱히 문제가 되진않습니다.

감사합니다.
