### ISSUE TITLE
CLI과 web 호환 문제

### ISSUE THREAD

**Issue by Shoninto** [ai-starthon/AI_Starthon2019#208]
**Informations**

#### WEB
- **Brower (chrome, firfox, etc)**:  chrome
- **URL**: https://nipa.nsml.navercorp.com/settings/group/team_287

**What is your NSML login ID?**
Shoninto

**Question**
web에서 nsml 로그인을 하고 settings에 들어가면 team_287이 web과 호환된다고 설정되어 있습니다. 그러나 CLI에서는 team이 다음과 같습니다.
C:\nsml_client.windows.amd64.hack>nsml teams
team_31
따라서 CLI에서의 팀이 team_31이기에 web과 상호작용이 안 됩니다. CLI에서 작업한 결과물이 web에 뜨지 않습니다. 해결방안을 제시해 주십시오.

**Comment by nsml-admin** [comment]
안녕하세요. 
해당 문제는 저희측에서 두번 등록하여 생긴 현상입니다...!

CLI 로그인시에  Shoninto  이 계정으로 들어가면 웹이랑 같은 화면을 보실수 있습니다.
team_31 에 있는 세션들은 전부 team_287 으로 옮겨드리도록 하겠습니다.

**Comment by nsml-admin** [comment]
접속해보시고 이상있을시 말씀해주세요!

**Comment by nsml-admin** [comment]
CLI일 경우 로그아웃 후 >> Shoninto 이걸로 접속해야합니다.

**Comment by Shoninto** [comment]
> 접속해보시고 이상있을시
