### ISSUE TITLE
Credit 소진상황에 대한 질문

### ISSUE THREAD

**Issue by theoseo** [ai-starthon/AI_Starthon2019#211]
크레딧 정책을 숙지 하지 못하고 작업하다 크레딧을 소진했습니다.
추가적인 충전이나 Submit을 위한 충전도 아예 안되는 건가요?

**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**Question**

**Comment by jungwoo-ha** [comment]
@theoseo 

크레딧 정책관련해서는 대회 시작 전부터 충분히 설명드렸고 대회 초반에 1회 추가 지급공지드리면서 태스크 이슈가 아닌 한 추가 지급이 어렵다는 점을 미리 말씀을 드렸었는데요. 크레딧 사용을 전략적으로 진행한 팀들이 많기 때문에 현시점에서 추가 지급은 어려울 것 같습니다. 이해 부탁드리겠습니다.

**Comment by theoseo** [comment]
> @theoseo
> 
> 크레딧 정책관련해서는 대회 시작 전부터 충분히 설명드렸고 대회 초반에 1회 추가 지급공지드리면서 태스크 이슈가 아닌 한 추가 지급이 어렵다는 점을 미리 말씀을 드렸었는데요. 크레딧 사용을 전략적으로 진행한 팀들이 많기 때문에 현시점에서 추가 지급은 어려울 것 같습니다. 이해 부탁드리겠습니다.

가장 중요한 사항을 가장 늦게 알았네요;;;
답변 감사드립니다!
