### ISSUE TITLE
session kill

### ISSUE THREAD

**Issue by tae-ha** [ai-starthon/AI_Starthon2019#220]
/bin/bash: line 1: 52 Killed python -u train.py
지금 몇번 nsml run을 해봤는데 터미널에 위 처럼 출력되면서 세션이 죽고 메일로 OOM Killer로 인해 죽었다고 안내가 왔는데 OOM Killer가 세션을 kill하는 기준이 뭔지 알 수 있나요? 제가 run할 때 설정한 memory보다 크면 kill 당하는건가요?

**Comment by nsml-admin** [comment]
네 맞습니다.

run 할때 설정한 memory보다 큰 사이즈를 사용하려고 하면 OOM 에러가 발생하면서 세션은 종료되게 됩니다.
