### ISSUE TITLE
14번 inpainting 문제의 submit 시 주어지는 데이터에 대해 문의드립니다.

### ISSUE THREAD

**Issue by HotaekHan** [ai-starthon/AI_Starthon2019#231]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**Question**
#129 의 내용을 참고했었는데요.
submit -t로 확인해본 결과, 주어지는 mask 데이터의 min값이 -0.1686, -0.2706인 샘플들이 있습니다. 픽셀값으로 환산해보면 106, 92정도인데요. 윗 답변같이 127, 255 값만 가지는 건 아닌 것 같습니다.
그리고 혹시, 주어지는 masked 데이터도 위와 같이 127값을 가지지 않는 mask가 곱해진 데이터가 불러와지는건가요??
혹시 의도를 하신건지, 데이터에 오류가 있는건지 궁금합니다.

**Comment by youngjung** [comment]
안녕하세요,

제보 감사합니다. 말씀하신 오차는 jpeg artifact로 보입니다.
이 오차가 evaluation에 미치는 영향은 tolerable 수준이겠지만 정확한 계산을 원하실테니,
TestDataset의 mask부분에 0.5로 threshold쳐서 0, 1로 갈라서 쓰는것으로 보정하시면 되겠습니다.
https://github.com/ai-starthon/AI_Starthon2019/blob/844b69910cc4ab19b7eed21fcaa8923e598684fd/14_ig5_inpaint/data_local_loader.py#L50
이 아래에
```python
mask = (mask > 0.5).float()
```
을 추가하시면 되겠습니다.
submit 해보니 다행히도 비슷하게 나오는군요 :)
