### ISSUE TITLE
credit 0인 상태에서 submit

### ISSUE THREAD

**Issue by aweek43** [ai-starthon/AI_Starthon2019#244]
현재 모델 학습을 끝내고 submit만 하면 되는 상황인데 credit을 모두 소진했습니다.
모델 2개 submit용의 credit을 받거나 CPU로 submit할 방법이 있을까요?

**Comment by aweek43** [comment]
submit해야 할 모델은
nsml submit team_4/12_idet_food/21 51
nsml submit team_4/10_idet5_food/34 46
두개 입니다...

**Comment by bluebrush** [comment]
@aweek43 님, #246 참고부탁드립니다.
