### ISSUE TITLE
submit 시 Error: Session does not respond 문제

### ISSUE THREAD

**Issue by aweek43** [ai-starthon/AI_Starthon2019#249]
submit 시 1시간 동안 inference하다가 Error: Session does not respond가 나오며 종료됩니다.
같은 코드와 모델로 며칠전에는 잘 submit 되어서 최적화문제가 아닌것 같습니다.
credit이 부족하여 --test을 하지 못했습니다.
nsml submit team_4/10_idet5_food/34 46  으로 submit했습니다.
혹시 사용자가 몰려서 그럴수도 있을까요?

**Comment by nsml-admin** [comment]
안녕하세요.

team_4/10_idet5_food/34 , 46  세션,모델로 예전에는 submit이 잘되었다는말씀인가요?

그게 아니면 예전에 잘 실행되었다는 세션네임을 알려주시기바랍니다.

**Comment by aweek43** [comment]
다른 세션이었습니다. 현재 해당세션을 삭제해서 세션네임은 기억이 나지 않습니다...
또한 inference부분은 baseline에서 수정하지 않았습니다.
