### ISSUE TITLE
사업설명회 필수 참석 여부

### ISSUE THREAD

**Issue by codertimo** [ai-starthon/AI_Starthon2019#252]
오늘 대회 순위를 통해서 결선에 진출한 팀들은 내일 사업설명회에 반드시 참가해야 하나요?

1. 내일 사업설명회 참석이 필수인가요?
2. 반드시 참가 팀원들 중에 한명이 참석해도 되나요 아니면 같은 회사에 다른 분이 참석하실 수 있나요?

감사합니다.

**Comment by aistarthonwaywai** [comment]
안녕하세요. 대회 사무국입니다.

1. 사업설명회는 사업화 지원기업 선정을 위해 필요한 내용을 안내하오니 되도록 참석해 주시기 바라며, 부득이한 사유로 참석이 어려우신 경우에는 참조하실 수 있는 자료를 추후 안내해 드릴 예정입니다.

2. 팀원 전원 참석하셔도 되고, 팀원 중 일부(한명)가 참석하셔도 괜찮습니다. 
   단, 참가신청해 주신 팀원만 참석이 가능하십니다.

고맙습니다.

**Comment by hoondental** [comment]
시간이 어떻게 되나요?

**Comment by aistarthonwaywai** [comment]
사업설명회는 내일 오후 3시 네이버 본사 2층 커넥트홀에서 진행될 예정입니다.
대회가 종료되면 대상팀들에게 별도 메일로 안내드릴 예정입니다.
