### ISSUE TITLE
접속 오류

### ISSUE THREAD

**Issue by escherlee** [ai-starthon/AI_Starthon2019#256]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:
- **Full command line**: 
nsml login 시 오류입니다.
ping과 telnet은 정상입니다.
ping nipa-cli.nsml.navercorp.com
telnet nipa-cli.nsml.navercorp.com 18553

INFO[2019/08/01 16:34:16.512] could not login: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid" 
FATA[2019/08/01 16:34:16.512] please check your network connectivity by using 'ping nipa-cli.nsml.navercorp.com' and 'telnet nipa-cli.nsml.navercorp.com 18553

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**What is name of session in problem? (bug message or screenshot)**

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by bluebrush** [comment]
@escherlee 님, 불편을 드려서 죄송합니다. #257 참고부탁드립니다.

**Comment by escherlee** [comment]
감사합니다. 수고하셨습니다.
