### ISSUE TITLE
[최종 문제 선정 문의] STT 문제 포함 여부

### ISSUE THREAD

**Issue by kimdongjin** [ai-starthon/AI_Starthon2019#27]
20_scls_stt baseline code가 안보이는데,
STT 문제가 최종 문제에서 제외된 건가요?

**Comment by bluebrush** [comment]
STT문제는 현재, baseline에 대한 추가 검증 중입니다. 완료되면 즉시 upload될 예정입니다. 지연되어 죄송합니다.

**Comment by bluebrush** [comment]
@kimdongjin 님, 20번 문제의 baseline upload되었습니다. 지연되어 죄송합니다.
