### ISSUE TITLE
nsml stop 이슈

### ISSUE THREAD

**Issue by singetta** [ai-starthon/AI_Starthon2019#28]
안녕하세요.
nsml과 베이스라인 코드 오픈 이후 테스트 중인데요.
nsml run 이후 아래와 같이 session이 보이는 상태에서 nsml stop을 하니 fail이 됐다고 나오는데요.
해결 방법이 없을까요?
에러 msg는 아래와 같습니다.

12_idet_food_baseline>nsml ps

Name                    Created          Args    Status     Summary    Description    # of Models    Size    Type
----------------------  ---------------  ------  ---------  ---------  -------------  -------------  ------  ------
team_23/12_idet_food/2  Not created yet          Allocated                            0              0       normal

12_idet_food_baseline>nsml stop team_23/12_idet_food/2
Stopping team_23/12_idet_food/2 is failed
Error: Session error: 'Failed to stop session [team_23/12_idet_food/2]'
time="2019/07/22 18:32:14.345" level=fatal msg="Internal server error"

**Comment by nsml-admin** [comment]
안녕하세요.

위와같은 경우 `nsml rm -f `로 해주시면 삭제 됩니다. (제가 지워드렸습니다)

**Comment by singetta** [comment]
확인 감사합니다. 해당 이슈 Close하겠습니다.
