### ISSUE TITLE
NSML에서 stop이 되지 않는 문제 

### ISSUE THREAD

**Issue by heypaprika** [ai-starthon/AI_Starthon2019#30]
NSML로 submit을 하였는데, 

Usage: nsml logs [OPTIONS] SESSIONError: Invalid value for "SESSION": Cannot logs [team_208/7_icls_face/3] (Only nsml rm is valid for submit sessions)

라는 error가 뜨고, 세션 정지가 되지 않습니다. 해결방법이 있을까요?

**Comment by noowad93** [comment]
저도 비슷한 이슈가 있습니다.

Session을 stop하려고 하는데,
Stopping team_89/17_tcls_intent/1 is failed
Error: Session error: 'Failed to stop session [team_89/17_tcls_intent/1]'
FATA[2019/07/22 19:01:02.522] Internal server error
와 같이 세션 정지가 되지 않습니다.

**Comment by sooheon** [comment]
동일한 현상 보입니다. 참고로 저는 `nsml run` 명령 주고 바로 SIGINT 보내서 `INFO[2019/07/22 19:04:29.155] run aborted: Interrupted by user` 라는 로그 확인 했습니다.
```
> nsml stop $SESSION
Stopping team_86/6_vcls_age/1 is failed
Error: Session error: 'Failed to stop session [team_86/6_vcls_age/1]'
FATA[2019/07/22 19:13:44.334] Internal server error                        

> nsml logs $SESSION
INFO[2019/07/22 19:16:58.787] ****************************************************************************** 
INFO[2019/07/22 19:16:58.788] * Interactive session will be terminated automatically after 30 minutes      * 
INFO[2019/07/22 19:16:58.788] * If you don't want to see this message, please use --hide-client-log option * 
INFO[2019/07/22 19:16:58.788] ****************************************************************************** 
Error: No such container: 
Error: An error occurred while calling a process on the docker
FATA[2019/07/22 19:16:59.609] Internal server error                        
```

**Comment by heypaprika** [comment]
그리고 nsml rm 은 제 nsml 버전에서는 없는 명령어입니다. 이전 버전의 nsml을 깔면 되는 문제인가요?
