### ISSUE TITLE
github id 추가등록 가능한가요?

### ISSUE THREAD

**Issue by Karnian** [ai-starthon/AI_Starthon2019#39]
처음 팀 등록 당시 팀장 깃헙 아이디만 등록한 상태인데

팀원 아이디를 추가등록 할 수 있나요?

메일로 받은 http://naver.me/FuJjPoku 해당 링크의 경우 아이디 적는 란이 하나밖에 없어서

그곳에 팀원 아이디를 적으면 기존 아이디가 등록 해제될까 싶어 먼저 여쭈어봅니다.

**Comment by nsml-admin** [comment]
등록할 팀원이 팀등록당시 등록했던 요청서에 있다면,

아래 등록할 팀원 
깃헙 계정과 이름 이메일을 dl_nsml_alpha@navercorp.com 여기로 보내주세요
확인 후 등록해드리겠습니다.

**Comment by Karnian** [comment]
넵 메일 보냈습니다.
