### ISSUE TITLE
등록 github id 수정요청

### ISSUE THREAD

**Issue by jihobak** [ai-starthon/AI_Starthon2019#43]
팀명:blowfish
이름:박지호
Id: jihobak
‘jiho bak’-> jihobak입니다

**Comment by nsml-admin** [comment]
네 수정되었습니다 확인부탁드려요 ~

**Comment by MachinaBlack** [comment]
@nsml-admin 
저도 부탁드립니다.
팀명: 마키나블랙
이름: 김도한
Id: DohanKim
dohankim -> DohanKim입니다

**Comment by nsml-admin** [comment]
네 수정되었습니다.
