### ISSUE TITLE
19번 문제 baseline 테스트

### ISSUE THREAD

**Issue by SAMHEO** [ai-starthon/AI_Starthon2019#44]
19번문제 baseline 테스트를 해보려고 실행 한 결과 이런 에러 메세지가 나옵니다

Error: Invalid value: Dataset not found: nipa_mrc
FATA[2019/07/22 19:39:39.303] Internal server error

혹시 데이터셋을 어디서 따로 얻어야 하는건가요?

**Comment by bluebrush** [comment]
안녕하세요. dataset 이름이 잘못된 것 같습니다. (dataset 이름에 번호를 붙이는 과정에서 readme가 반영되지 않아서 오류가 있었습니다. 불편을 드려서 죄송합니다.)
dataset이름 : 19_tcls_qa

**Comment by SAMHEO** [comment]
확인했습니다 감사합니다 :)
