### ISSUE TITLE
.Error: An error occurred while initializing user information.

### ISSUE THREAD

**Issue by escherlee** [ai-starthon/AI_Starthon2019#48]
**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**: Ubuntu 18.04.2
- **client version(please show nsml --version)**: 2019-07-22T20:39:08+09:00
- **Full command line**: nsml run -d 1_reg_dust -i

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**
escherlee

**What is name of session in problem? (bug message or screenshot)**
INFO[2019/07/22 22:38:51.148] .nsmlignore check - start                    
INFO[2019/07/22 22:38:51.148] .nsmlignore check - done                     
INFO[2019/07/22 22:38:51.502] file integrity check - start                 
INFO[2019/07/22 22:38:51.502] file integrity check - done                  
INFO[2019/07/22 22:38:51.503] README.md 872 B - start                      
INFO[2019/07/22 22:38:51.503] README.md 872 B - done (1/5 20.00%) (872 B/9.5 KiB 9.01%) 
INFO[2019/07/22 22:38:51.503] data_loader.py 1.0 KiB - start               
INFO[2019/07/22 22:38:51.503] data_loader.py 1.0 KiB - done (2/5 40.00%) (1.9 KiB/9.5 KiB 20.07%) 
INFO[2019/07/22 22:38:51.503] evaluation.py 2.3 KiB - start                
INFO[2019/07/22 22:38:51.503] evaluation.py 2.3 KiB - done (3/5 60.00%) (4.2 KiB/9.5 KiB 44.48%) 
INFO[2019/07/22 22:38:51.503] main.py 5.0 KiB - start                      
INFO[2019/07/22 22:38:51.503] main.py 5.0 KiB - done (4/5 80.00%) (9.2 KiB/9.5 KiB 97.77%) 
INFO[2019/07/22 22:38:51.503] setup.py 216 B - start                       
INFO[2019/07/22 22:38:51.504] setup.py 216 B - done (5/5 100.00%) (9.5 KiB/9.5 KiB 100.00%) 
.Error: An error occurred while initializing user information. Please contact dev team
FATA[2019/07/22 22:38:52.259] Internal server error                        

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by nsml-admin** [comment]
안녕하세요,

현재는 처리되었습니다 다시한번 해보실래요?

불편을드려 죄송합니다.

**Comment by escherlee** [comment]
잘 동작합니다.
감사합니다.
