### ISSUE TITLE
사업화 지원 대상

### ISSUE THREAD

**Issue by kyuhyoung** [ai-starthon/AI_Starthon2019#5]
아래의 "상세 참가 자격 보기" 링크를 따라가 보면, (사업화 지원 대상)에는 "창업 후 3년 미만의 기업" 이라고 되어 있는데, "3년 이상의 기업"은 경진대회만 참가 할 수 있고, 사업화 지원 신청은 할 수 없는 건가요? 

https://docs.google.com/document/d/1amGM9zZI77Jshdi1TnTNjFHNZNyFeUoOSCB_9hDXoP0/edit?usp=sharing

지원 자격 상세
 
	- (경진대회 참여자격) 국내외 기업, 대학, 대학(원)생 연구기관, 산‧학‧연 컨소시엄 등
 
	- (사업화 지원 대상) 경진대회 상위 입상 팀 중, AI 산업 활성화 및 창업 촉진 목적에 따라 사업화 지원 사업 제출서류 접수 마감 기준 인공지능 기술을 활용한 스타트업, 벤처‧중소기업 또는 예비 창업자등을 기준으로 함
  	* 벤처·중소기업은 창업 후 3년 미만인 기업임
  	* 예비 창업자의 경우 사업화 지원사업 수행계획서 접수 전까지 창업(사업자등록 및 법인 설립)이 가능한 자
   	* 대학(원)생의 경우 소속 대학 산학협력단을 통해 참여하는 경우 지원 가능
 
 
	- 외국 소재 기관(기업, 대학, 연구소 등)의 경우 경진대회는 자유롭게 참가 가능하나, 사업화 지원을 받기 위해서는 주관기관 대표이사가 대한민국 국적자인 벤처‧중소기업을 주관기관으로 컨소시엄 형태로 참여하여야 함

**Comment by aistarthonwaywai** [comment]
안녕하세요.

3년 이상된 기업도 경진대회 참가 가능하시며 최종 20개팀으로 선발되시면 사업화 지원도 받으실 수 있습니다. 

아직 참가신청을 하지 않으셨다면 참조하시어 참가신청 부탁드립니다.

감사합니다.

**Comment by kyuhyoung** [comment]
> 안녕하세요.
> 
> 3년 이상된 기업도 경진대회 참가 가능하시며 최종 20개팀으로 선발되시면 사업화 지원도 받으실 수 있습니다.
> 
> 아직 참가신청을 하지 않으셨다면 참조하시어 참가신청 부탁드립니다.
> 
> 감사합니다.
