### ISSUE TITLE
경량화 문제 parameter 수 측정방법 문의

### ISSUE THREAD

**Issue by tae-ha** [ai-starthon/AI_Starthon2019#50]
경량화 관련 문제들에서 Parameter 수는 어떤식으로 세시는 건가요?
keras를 예로들면 keras.backend.count_params()로 측정하시는 건가요?
각 프레임워크(keras, pytorch, tensorflow) 별로 어떤방식으로 모델의 Parameters를 세는지 알려주시면 감사하겠습니다.

**Comment by bibekkk** [comment]
import numpy as np
#Function to compute model parameters
def model_parameters(model):
    return sum([np.prod(p.size()) for p in model.parameters()])/ 1e6

저는 이걸로 측정하고 잇어요!! 이렇게 하면 local에서 parameter수가 2.10 M(million) 나와요..하지만 nlsml에서 돌리면 20971520.0 정도로 나와서 save못하고 잇어요!! 어떻게 해 야 하나요?

**Comment by times2049** [comment]
저도 로컬에서 측정할때 5M을 넘지 않는데 세이브가 안됩니다 어떻게 해야하나요

**Comment by tae-ha** [comment]
@bluebrush 혹시 이 문제는 내부적으로 논의 중이신건가요? 이틀이 지났는데 답이 없으셔서요..ㅠㅠ

**Comment by bluebrush** [comment]
@tae-ha 
불편을 드려서 죄송합니다. 현재, parameter 갯수 제한 방법은 parameter x 4의 값으로 SIZE 제한을 하고 있습니다. 2M개의 파라미터의 경우, 2M x 4(bytes) = 8MB (메가바이트)로 제한하고 있습니다. 용량확인을 통하여 save 가능 여부를 확인 하실 수 있을 것 같습니다.

**Comment by tae-ha** [comment]
@bluebrush 그러면 5M 제한이 있는 테스크에서는 모델사이즈가 20MB가 넘지 않아야 저장이 된다는 말씀이신가요?

**Comment by nsml-admin** [comment]
안녕하세요.

정확하게 말씀드리면, 모델사이즈보다는

`nsml.bind(save=save)`로 넘겨지는 `save`함수에서 directory위치를 받고 그 하위에 파일들을 저장할텐데요(모델파일포함),

그럴때 directory 전체의 사이즈가 20MB이내여야 합니다.

감사합니다.

**Comment by tae-ha** [comment]
@nsml-admin 저희가 내부적으로 모델을 저장해보면 모델 크기가 10MB 이하로 나오는데 nsml 상에서는 저장이 안됩니다. 그러면 디렉토리에 모델이외에 다른 파일들도 저장이 되서 그런건가요?

**Comment by nsml-admin** [comment]
@tae-ha 

디렉토리 안에있는 모델 이외의 다른 파일들도 저장되어서 그렇게 나오는것같습니다.

윗 댓글에 제가 말씀을 잘못드린점이 있는데요,

directory의 전체 사이즈체크를 하는게 아니고 directory안의 파일 하나하나가 20MB 넘는지 유무만 체크합니다.
