### ISSUE TITLE
3번문제 현재 1위인데 전체랭킹 보드에 반영되지 않고 있습니다. 1그룹입니다.

### ISSUE THREAD

**Issue by byc3230** [ai-starthon/AI_Starthon2019#51]
모두의비전, 1그룹입니다. 3_cls_crane2 현재시각 랭킹 1위인데, 전체 랭킹에 아예 반영되지 않고 있습니다.

랭킹 1위 , 0.0860692102928 | team_284/3_cls_crane2/2/133

**Comment by nsml-admin** [comment]
네 안녕하세요 전체랭킹보드는 시간 단위로 현재 업데이트 되고 있습니다.
지금은 반영된것으로 보입니다.
