### ISSUE TITLE
nsml webui 에서 seesion 기록 삭제 시도시 실패합니다.

### ISSUE THREAD

**Issue by junwoopark92** [ai-starthon/AI_Starthon2019#53]
nsml webui에서 세션 status가 exited일때 삭제시도를 할시 아래와 같은 에러가 발생합니다.
![image](https://user-images.githubusercontent.com/26558158/61662773-0b289d00-ad0a-11e9-8b5a-f987313cede9.png)

불필요한 세션 기록들 제거해서 정리하려고하는데 어떻게 해야하나요?

**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**Question**

**Comment by bluebrush** [comment]
@junwoopark92 님. 
세션 삭제는 두 가지 방법을 지원하고 있습니다. 
1. CLI: nsml rm  [세션명]   (또는) nsml rm -f [세션]
2. 웹 UI

문제가 지속되면 세션명을 알려주시면 조치하겠습니다.

**Comment by junwoopark92** [comment]
> @junwoopark92 님.
> 세션 삭제는 두 가지 방법을 지원하고 있습니다.
> 
> 1. CLI: nsml rm  [세션명]   (또는) nsml rm -f [세션]
> 2. 웹 UI
> 
> 문제가 지속되면 세션명을 알려주시면 조치하겠습니다.

CLI에서 nsml rm 으로 시도하면 정상적으로 삭제됨을 확인하였습니다.

감사합니다~!
