### ISSUE TITLE
랭킹 반영이 되지 않습니다.

### ISSUE THREAD

**Issue by Karnian** [ai-starthon/AI_Starthon2019#54]
Nsml submit 한지 수시간이 지났는데 랭킹 반영이 되지 않습니다.

다른 글에서 매 시간 반영된다고 봤는데 특정 시간대만 동작하나요?

**Comment by bluebrush** [comment]
현재 leaderboard는 2단계로 동작하고 있습니다. 
각
1.  문항별 leaderboard  (실시간 집계)
2. 종합 leaderboard (배치 집계)
배치 집계 간격이 넓어 불편을 드린 것 같습니다. 금일 중에 개선하도록 하겠습니다.
