### ISSUE TITLE
캐글처럼 리더보드용 data set과 대회 성적용 data set이 나누어 져 있나요?

### ISSUE THREAD

**Issue by comlhj1114** [ai-starthon/AI_Starthon2019#56]
안녕하세요, 지금 각 문제별 리더보드에 보이는 성적이 실제 대회 성적으로 이어지는지, 아니면 리더보드에 보이는 성적은 네이버에서 만든 validation data set이고, 실제 test data set으로 최종 성적을 내는건지 궁금합니다.

**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**Question**

**Comment by bluebrush** [comment]
@comlhj1114  현재 leaderboard 점수는 최종결과 입니다. 현 leaderboard 점수로 최종 순위 확정됩니다. :)
