### ISSUE TITLE
18일에 시행하는 사전교육 시간표를 알고 싶습니다.

### ISSUE THREAD

**Issue by hanboa1026** [ai-starthon/AI_Starthon2019#6]
교육시작 및 종료시간이 언젠지 궁금합니다

**Comment by taehee3088** [comment]
안녕하세요. 

사전교육은 **7/18(목) 15:00-17:00** 의 일정으로 진행합니다. 

**장소: 네이버 본사 그린팩토리 2층, 커넥트홀**

14:30 ~ 15:00 | 참석자 확인 및 입장
-- | --
15:00 ~ 15:20 | 오리엔테이션
15:20 ~ 16:00 | 문제 정의 및 설명 / 질의 응답
16:00 ~ 16:20 | 휴식 시간
16:20 ~ 17:00 | NSML 사용법 / 질의 응답

감사합니다.
