### ISSUE TITLE
github id 등록 요청

### ISSUE THREAD

**Issue by yhjungkorea** [ai-starthon/AI_Starthon2019#60]
안녕하세요.
저희 마음팀의 2명에 대한 github id 등록을 요청드립니다.

**github id**
박시화  |  astrayne@korea.ac.kr   |  astrayne
최정원  |  jedo0328@naver.com  |  GartenChoi

**Comment by nsml-admin** [comment]
네 등록되었습니다. 확인부탁드려요 !

**Comment by yhjungkorea** [comment]
감사합니다.

2019년 7월 23일 (화) 오후 1:26, nsml-admin <notifications@github.com>님이 작성:
