### ISSUE TITLE
사업화 지원 대상 - 요건

### ISSUE THREAD

**Issue by sunghooncho88** [ai-starthon/AI_Starthon2019#7]
지원 자격 상세 내용에 따르면 사업화 지원 대상으로 창업 후 3년 미만 기업으로 되어 있는데, 창업 3년 이상 기업은 사업화 지원 신청 대상에서 제외되는지 확인 요청 드립니다.

**Comment by aistarthonwaywai** [comment]
안녕하세요.

3년 이상된 기업도 경진대회 참가 가능하시며 최종 20개팀으로 선발되시면 사업화 지원도 받으실 수 있습니다.

아직 참가신청을 하지 않으셨다면 참조하시어 참가신청 부탁드립니다.

감사합니다.
