### ISSUE TITLE
github id 등록 요청

### ISSUE THREAD

**Issue by Shoninto** [ai-starthon/AI_Starthon2019#70]
안녕하세요.
저희 Maxsecure팀의 1명에 대한 github id 등록을 요청드립니다.

github id
송현철 | into0216@gmail.com | Shoninto

**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**Question**

**Comment by nsml-admin** [comment]
네 등록되었습니다.
