### ISSUE TITLE
Tensorflow 2.0b1 사용 가능 여부

### ISSUE THREAD

**Issue by alanpurple** [ai-starthon/AI_Starthon2019#75]
Tensorflow 2.0 사용이 가능한지 문의드립니다. 안되는 거로 보입니다만

**Comment by nsml-admin** [comment]
사용이 가능합니다.

직접 도커이미지를 빌드해서 사용하시거나 setup.py에 필요한 버전을 명시하고 실행하면 됩니다.

추천드리는 방법은 직접 도커이미지를 빌드하신후 사용하시는걸 추천드립니다.

**Comment by alanpurple** [comment]
@nsml-admin 

감사합니다.
