### ISSUE TITLE
inpaint(14번) data

### ISSUE THREAD

**Issue by Soongja** [ai-starthon/AI_Starthon2019#78]
14번 문제 inpaint 데이터 readme 올려주신 것 잘 봤습니다. 그런데 input 이미지에서 마스크 처리되 부분이 회색으로 나타나 있는데, 값이 0이 아닌 것인가요? train과 test 시에 mask에 normalizing을 해주는 부분에서 혼동이 오는데, mask 영역 값들에 대한 설명 해주시면 감사하겠습니다.

추가적으로, 14번문제 train 과정에서 read_prediction_gt를 할 때에는(main.py 176~177줄) load_image 후 normalize를 하는 반면, evaluation 시에는 (evaluation.py 31줄) read_prediction_gt에서 load_image만 하고 있는데, 최종적으로 normalize를 안 한 것으로 채점이 되니 그렇게 생각하고 앞 과정을 수정하면 되는지 알고 싶습니다.

**Comment by Soongja** [comment]
추가적으로, 14번문제 train 과정에서 read_prediction_gt를 할 때에는(main.py 176~177줄) load_image 후  normalize를 하는 반면, evaluation 시에는 (evaluation.py 31줄) read_prediction_gt에서 load_image만 하고 있는데, 최종적으로 normalize를 안 한 것으로 채점이 되니 그렇게 생각하고 앞 과정을 수정하면 되는지 알고 싶습니다.

**Comment by youngjung** [comment]
안녕하세요, 제보 감사합니다.
evaluation.py 31줄은 채점시 사용되지 않습니다.
local_eval()에서 나오는 값이 최종 채점과 동일합니다. (=[dataloader가 주는 GT](https://github.com/ai-starthon/AI_Starthon2019/blob/c028b635dd2213f0ed0d81fe03de84f90a08f722/14_ig5_inpaint/main.py#L79)를 기준으로 쓰시면 됩니다)

**Comment by youngjung** [comment]
아, 뒤에 설명하느라 까먹었군요.
dataloader를 까보시면 cutout()에서 마스크 작업의 세부내용을 알 수 있습니다.
mask는 1/0으로 되어있습니다.
x_input은 normalize 후 mask를 곱해서 회색이 0입니다.

**Comment by Soongja** [comment]
답변 감사합니다.
