### ISSUE TITLE
[요청] NSML 랭킹보드에 20개 문제별 랭킹 페이지도 만들어주세요

### ISSUE THREAD

**Issue by artlab-ai** [ai-starthon/AI_Starthon2019#80]
안녕하세요
현재 리더보드에는 총점 기준으로 랭킹이 나와있는데요,
https://nipa.nsml.navercorp.com/ranking
20개의 문제별 랭킹 페이지도 만들어 주시면 
대회참가자/비참가자가 현재 경쟁 상황을 판단하기 좋을 것 같습니다.
부탁 드리겠습니다! 감사합니다.

**Comment by bluebrush** [comment]
@artlab-ai 님, 해당 기능은 개발중에 있으며, 내일 쯤 반영 예정입니다. :)

**Comment by nsml-admin** [comment]
아래와 같은 URL로 들어가시면 보실수 있습니다.
https://nipa.nsml.navercorp.com/ranking/partial?datasetName=16_tcls_movie

**Comment by nsml-admin** [comment]
https://github.com/ai-starthon/AI_Starthon2019/issues/109 여기이슈로 이동하도록 하겠습니다.
