### ISSUE TITLE
트레이닝 및 submit 테스트는 정상 작동하지만 submit에서 오류 발생

### ISSUE THREAD

**Issue by zeze-zzz** [ai-starthon/AI_Starthon2019#81]
**Informations**
#### CLI
- macOS 10.14.5
- client built 2019-07-22T20:39:08+09:00

**What is your NSML login ID?**
`zeze-zzz`

**Question**
```
nsml submit team_236/15_ig_super/12 3_1000
.......
Building docker image. It might take for a while
..........Inference the test set. The inference should be completed within 3600 seconds.
...Error: Fail to get prediction result: team_236/15_ig_super/12/3_1000
FATA[2019/07/23 19:03:46.770] Internal server error 
```
`nsml run`을 사용한 트레이닝과 `nsml submit -t`를 통한 테스트가 모두 정상적으로 완료한 뒤에 제출 시 위와 같은 에러 메시지가 출력됩니다. 어느 사유로 인해 에러가 발생하였는지 (또는 NSML 시스템 버그인지) 확인할 방법이 없습니다.

**Comment by MachinaBlack** [comment]
안녕하세요. 저희도 같은 현상이 발생하고 있습니다.
@nsml-admin 위 문제에 대한 답변을 부탁드리겠습니다.

**Comment by codertimo** [comment]
@nsml-admin 저 역시 해당 문제에 있습니다. nsml test에서 error trace를 볼 수 있는 방법이 없을까요?

**Comment by bluebrush** [comment]
@zeze-zzz @MachinaBlack @codertimo 님, 
불편을 드려서 죄송합니다.  
" ...Error: Fail to get prediction result: ..." 오류에 대한 원인분석 및 대응을 진행중입니다. 
현재, prediction file 크기 문제로 추정하여 분석하고 있습니다.

**Comment by nsml-admin** [comment]
@zeze-zzz  문제가 발생했던 세션네임으로 서브밋을 대신해드렸습니다.
서버관련 이슈였었고 조치가 완료된상태라서 submit을 하면 정상동작함을 확인 할 수 있습니다.
@codertimo @MachinaBlack  문제가 발생했던 세션네임과 실행했던 명령어를 https://github.com/ai-starthon/AI_Starthon2019/issues/102 이슈에 코멘트로 달아주시면 nsml팀에서 `submit`을 대신해드리겠습니다.

이이슈는 https://github.com/ai-starthon/AI_Starthon2019/issues/102 이쪽에서 계속 진행하겠습니다.
