### ISSUE TITLE
다른 종목의 데이터셋 활용 가능 여부

### ISSUE THREAD

**Issue by zeze-zzz** [ai-starthon/AI_Starthon2019#82]
**Question**
A 종목의 데이터셋에서 트레이닝한 모델을 B 종목에서 `nsml.load`로 불러와서 활용해도 무방한지 궁금합니다.
예) 음식 classification 모델을 -> 음식 detection에서 사용

**Comment by jungwoo-ha** [comment]
데이터셋 별로 바인딩된 구조인지라 원칙적으로 외부데이터 사용과 동일하게 간주될 수 있어 (문제 특성에 따라 test set이 동일하지 않을 수 있습니다) 해당문제에 주어진 데이터로만 학습된 모델만 사용하실 수 있습니다. 
즉.. 음식 분류 문제는 음식 분류 모델만 로딩, 타 태스크에 활용 금지 입니다.
