### ISSUE TITLE
submit 에러

### ISSUE THREAD

**Issue by hskim-solv** [ai-starthon/AI_Starthon2019#88]
.........Traceback (most recent call last):
  File "/app/src/main.py", line 5, in <module>
    nsml.nsml(obj={}, prog_name='nsml')
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/src/nsml_cli/nsml.py", line 637, in submit
    submit_session(ctx, session, checkpoint, verbose, test, entry, realm)
  File "/app/src/nsml_cli/sessions/eval_service.py", line 115, in submit_session
    user_args=None, gpus=DEFAULT_GPU_FOR_INFER
  File "/app/src/nsml_cli/sessions/eval_service.py", line 472, in _infer
    raise raised
  File "/app/src/nsml_cli/sessions/eval_service.py", line 394, in build_and_launch
    'exec', session.name, 'ls', '/tmp', encrypted=ctx.obj
  File "/app/src/nsml_cli/cluster.py", line 93, in docker
    return docker(self.address, *args, **kwargs)
  File "/app/src/nsml_cli/docker.py", line 91, in docker
    return _run_docker_cmd(args, interactive, err, **kwargs)
  File "/app/src/nsml_cli/docker.py", line 76, in _run_docker_cmd
    out = check_output(cmd, stderr=-2 if err else devnull)
  File "/usr/local/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker', '--config', '/tmp/team_73', '-H', 'tcp://10.41.41.219:2375', 'exec', '7465616D5F37335F3462373233306137333838373432373638653439306338323664613935396639', 'ls', '/tmp']' returned non-zero exit status 1.
FATA[2019/07/23 06:06:21.045] Internal server error

**Informations**
#### CLI
- **OS (Mac, Windows, Linux, etc) and version**:
- **client version(please show nsml --version)**:
- **Full command line**:

#### WEB
- **Brower (chrome, firfox, etc)**:
- **URL**:

**What is your NSML login ID?**

**What is name of session in problem? (bug message or screenshot)**

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by HotaekHan** [comment]
저도 동일한 증상입니다.
Command window에서는 위와 같은 log가 발생하고,
Web에서 확인을 해보면,

main.py: error: unrecognized arguments: --mode test --pause 1

위와 같은 error가 발생합니다. code에 arguments는 분명히 선언이 되어있고, run으로 동작시에는 정상적으로 argument값이 출력되는 것도 확인하였습니다.
submit할때만 위와 같은 문제가 발생하네요

**Informations
CLI**

**OS (Mac, Windows, Linux, etc) and version**: Ubuntu 16.04, Windows 10
**client version(please show nsml --version**): Built: 2019-07-22T20:39:08+09:00
**Full command line**: submit -t [session] [checkpoint]

**WEB**

**Brower (chrome, firfox, etc**): firefox
**URL:**

**What is your NSML login ID?**
HotaekHan

**What is name of session in problem? (bug message or screenshot)**
team_57/13_idet_car/75

Steps to reproduce the problem

What is the expected behavior?

Suggested solutions

**Comment by nsml-admin** [comment]
@times2049 @HotaekHan  위와같은 경우는 `nsml.paused`가 호출되기전에 에러가발생하거나 `nsml.paused`가 호출이 안된경우인데요, https://n-clair.github.io/nipa-docs/_build/html/ko_KR/contents/nsml_library/nsml_paused.html 이쪽을 참고해보시기 바랍니다.


참고로 `nsml.paused`가 호출되기 전에 에러가 발생하는 케이스는 대부분이 `train`데이터에 접근하다가 발생하는 경우가 많은데요, `submit`과 `submit --test`세션의 경우는 `train`데이터 자체가 없는 환경에서 실행됩니다. (`train`데이터에 접근하면 안됩니다)

또한 baseline들의 예제코드를 보면 좀더 명확한 이해가 되실것같습니다.

**Comment by HotaekHan** [comment]
@nsml-admin 안녕하세요? 말씀해주신대로 nsml.paused의 호출 위치를 조정을 해보아도 동일한 error가 발생합니다. 
현재 main.py의 흐름은 아래와 같습니다.

    Config 읽기 (yaml로 되어있는 config 파일을 읽습니다.)
    학습에 쓰일 변수설정
    cuda 설정 (gpu가 있으면 cuda를 사용하도록)
    Model 로드
    병렬화 설정 (Data parallel)
    Loss 설정
    Optimizer 설정
    Scheduler 설정
    NSML bind
    NSML paused
    만약 mode가 train이면
        Data load
        학습 진행

그리고 아무 관련이 없긴 할테지만 파일이름은 main.py가 아니라 다른 이름입니다.
또한 최초에 학습을 실행한 session에 복사된 코드는 순서에 문제가 있을 수 있는 코드입니다.
그래서 nsml.load를 통해서 학습을 실행한 session의 checkpoint를 불러오고, 이를 nsml.save로 저장하는 dummy session을 만든 뒤, 해당 dummy session을 submit에 이용하였습니다.
dummy session은 수정한 코드를 복사해서 session에 올라가니, 이렇게 하면 되겠다고 생각했어요.

혹시 어느 부분에서 문제가 발생하는건지 comment 가능하실까요?

**Comment by hskim-solv** [comment]
저는 베이스라인 기반으로 코드를 짰고 바꾼 부분은 모델코드와 torch.nn.DataParall만 바꿨습니다. 그랬는데도 에러가 납니다. nsml.paused관련문제가 아닌것 같은데 확인 부탁드립니다.

**Comment by nsml-admin** [comment]
@times2049  @HotaekHan 
재현가능한 방법을 알려주시면 디버깅후에 좀더정확한 답변을 드릴수 있을것같은데요,

학습 세션네임과 실행했던 커맨드, 
학습된걸 submit 했을때의 커맨드와 새로생긴 서브밋 세션네임을 알려주시면 될것같습니다.

**Comment by hskim-solv** [comment]
team_73/14_ig5_inpaint/104

nsml run -d 14_ig5_inpaint --shm-size 24G -g 2 -c 4

nsml submit -t team_73/14_ig5_inpaint/104 2

team_73/14_ig5_inpaint/114

**Comment by nsml-admin** [comment]
@times2049 
`nsml logs team_73/14_ig5_inpaint/114` 로 세션로그를 확인하면 에러스택을 확인 할 수 있고 디버깅이 가능할거라고 생각됩니다. (참고로 submit할때 gpu갯수는 무조건 1개로 할당됩니다)

**Comment by HotaekHan** [comment]
@nsml-admin 
학습 세션 네임: team_57/13_idet_car/88
학습 시 사용한 커맨드: 
nsml run -d 13_idet_car -e train_nsml.py -g 1 -c 4

서브밋 세션 네임: team_57/13_idet_car/89
서브밋 시 사용한 커맨드: 
nsml submit -t team_57/13_idet_car/88 0

**Comment by nsml-admin** [comment]
@HotaekHan 
`train_nsml.py` 파일에서 `from data.create_dataset import do_split_data`하는 부분이 있습니다.

여기에서 `--classes` argument만 받는데, 이부분에서 에러가발생한것같습니다.

**Comment by HotaekHan** [comment]
@nsml-admin logs로 출력을 해보아도, mode와 pause arguments가 없다는 에러만 발생하고 있습니다.
알려주신 사항 확인해볼께요!

**Comment by HotaekHan** [comment]
@nsml-admin 정상동작 확인되었습니다. 감사합니다.
