### ISSUE TITLE
등록되지 않은 계정으로 나옵니다.

### ISSUE THREAD

**Issue by cycos83** [ai-starthon/AI_Starthon2019#89]
대회 신청 당시에 github ID를 작성해서 제출하였는데 (1번 참가자)

등록되지 않은 사용자로 로그인이 되지 않습니다. (콘솔 및 NSML 싸이트 로그인)

제 메일로 안내메일들이 오는 것을 보면 신청은 정상적으로 이루어진것 같은데 확인 부탁드립니다.

한양대학교 서광원으로 등록 하였습니다

**Comment by nsml-admin** [comment]
안녕하세요

github 계정이 잘못 입력되어있었으며,
지금 등록되었습니다.
