### ISSUE TITLE
사전교육 불참시 관련 자료 공유

### ISSUE THREAD

**Issue by uohesha** [ai-starthon/AI_Starthon2019#9]
안녕하세요 해당일자에 팀원 전원이 지방출장을 가게 되어 관련 발표자료 링크 공유가 가능하실지 문의드립니다.

**Comment by aistarthonwaywai** [comment]
안녕하세요. 

사전교육에 부득이 참여하실 수 없는 분들을 위해 
당일 행사 내용을 녹화할 예정입니다.

행사 영상은 추후  참조하실 수 있도록 홈페이지에 공지 및 개별 안내 메일 보내드리도록 하겠습니다.

감사합니다.
