### ISSUE TITLE
submit 3문제 제출완료시 다른 문제 푸나요?

### ISSUE THREAD

**Issue by byc3230** [ai-starthon/AI_Starthon2019#91]
3문제 제출완료시 다른 문제 추가로 못 푸나요? 풀수는 있는데 submit 만 되거건지?

**Comment by socssg** [comment]
사전교육 영상 보시면 20문제 전부 풀어도 상관없다고 되어 있습니다 문제는 풀 수 있는데 점수계산은 상위 3문제에 대해서만 반영되는거 같아요

**Comment by bluebrush** [comment]
@byc3230 님, socssg님의 말씀 처럼 3개 이상의 문제를 푸셔도 상관없습니다. 3개 이상을 풀 경우, 상위 등수 3개 문제에 대해서 자동으로 점수 합산하게 됩니다.
