### ISSUE TITLE
Git아이디 등록요청드려요

### ISSUE THREAD

**Issue by bjo9280** [ai-starthon/AI_Starthon2019#93]
안녕하세요 git아이디 등록요청드립니다.

팀명: 링크제니시스
이름: 박주미 gitid: click16whd
이름: 이근호 gitid: henryyun

**Comment by nsml-admin** [comment]
안녕하세요
henryyun 이 계정은 존재해서 등록하였는데,
click16whd 이 계정은 잘못입력하신게 아닌지 확인부탁드려요!

검색하기 쉬운 방법은 
https://github.com/nsml-admin  < 이렇게 했을때 계정이 나오면 저희가 등록하기 쉬울것 같습니다. :)
