### ISSUE TITLE
미세먼지 문제 feature 설명 부족

### ISSUE THREAD

**Issue by alanpurple** [ai-starthon/AI_Starthon2019#98]
npy 데이터 14개 마지막 10개가 미세,초미세인데

미세,초미세,미세,초미세  순으로 되어 있는지
아니면 미세5개, 초미세 5개 순서인지 문의드립니다.

**Comment by jungwoo-ha** [comment]
(미세, 초미세) * 5 즉 번갈아서 나옵니다.

**Comment by alanpurple** [comment]
@jungwoo-ha 

감사합니다.
